### ISSUE TITLE
CTRL+SPACE not always working

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#10]
Hi,

It is sometimes required to type one character then remove it before auto-completion list appear.
Can you fix this, please?

Thanks a lot!
C.CLEAUD

**Comment by jcaillon** [comment]
This bug occurred when creating a new file and saving it with a correct progress *.extension*.

Since the buffer (= document) stays the same, the info on the current file are not updated and 3P doesn't recognize this file as a valid progress file.

Correct in the next release (v1.0.1)

**Comment by ccleaud** [comment]
Bug also coourred when opening an ABL source, going to line 30+ and press CTRL+SPACE.
Please ensure this case is also correced.
Thanks.

**Comment by jcaillon** [comment]
Yep, should be
