### ISSUE TITLE
Form with resize grip show the resize grip even when they are maximized

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#100]
The GUI convention with Windows is to hide the grip on maximized window.

This is because the grip only has sense on "normal" window, to allow user to change the size.
When in full screen, the user has no choice because the screen resolution are fixed values.

Thanks.

**Comment by jcaillon** [comment]
That's actually on improvement from the "classic" windows, since they can't be resized when on full size. In 3P the user has the choice to resize the ui even when it's maximize, you might want to reduce a bit for example.
