### ISSUE TITLE
Auto-completion menu pops up even when outside the main window

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#102]
# How to reproduce
## Case 1
1. open an OpenEdge source file in Notepad++
2. open the Notepad++ about box
3. click somewhere in the text
4. press CTRL+SPACE
## Case 2
1. open an OpenEdge source file in Notepad++
2. open the search box (CTRL+F)
3. press CTRL+SPACE

Thanks for all.

**Comment by jcaillon** [comment]
This is not a relevant bug sorry..
