### ISSUE TITLE
New procedure not always inserted at the correct place

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#103]
**How to reproduce**
1. open "1-before.p" in Notepad++ (see [attachments.zip](https://github.com/jcaillon/3P/files/531825/attachments.zip))
2. choose "Generate and revise code" --> "Insert New internal Procedure"
3. name it "DuplicateXXX"
4. make it private
5. validate
6. you'll see the procedure is inserted in the middle of the "Definitions" section

![1](https://cloud.githubusercontent.com/assets/7109720/19417368/47aaaa82-93ab-11e6-9d14-431e637d679c.PNG)

[attachments.zip](https://github.com/jcaillon/3P/files/531825/attachments.zip)

Thanks for fixing.
Regards.

**Comment by ccleaud** [comment]
This happens even if there are existing procedure in the source file.
Please not the "1-before.p" file has been generated by the AppBuilder.

**Comment by jcaillon** [comment]
It's inserted just before your EXTERNAL PROCEDURE (alphabetical order), which you placed in the definition section.
Correct your code by moving your procedures out of the definition block to solve this problem.
