### ISSUE TITLE
Proposed keywords are not all in uppercase

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#104]
My code defined an explicit stream named "sOut".
Somewhere in the code I typed "sO" and the auto-completion menu poped up.
I found strange not having SOAP-\* keywords in uppercase, unlike other keywords.

There are some other (see SAX-\* keywords).
There is also another strange "NO-CONVERT-" keyword (please note the trailing minus).

![1](https://cloud.githubusercontent.com/assets/7109720/19417623/dead1cc0-93b1-11e6-801a-b9289e2388c7.PNG)

Thanks for all.

**Comment by jcaillon** [comment]
Thx, fixed
