### ISSUE TITLE
Code explorer improvement proposal about private procedure / functions

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#106]
Instead of adding an icon on the right of the private procedure / function name, can you add an overlay to the entity type: a red circle conataining a white minus?

This is because the function "Duplicate..." doesn't clearly appears as private:
![2](https://cloud.githubusercontent.com/assets/7109720/19417730/a8a3ca5e-93b4-11e6-9312-7c5ddbfdd31d.PNG)

Thanks for considering this ticket.

**Comment by jcaillon** [comment]
I've slightly increased the opacity of the flags, this should do the trick.
The left icon is dedicated to represent the type of the item, I don't want to create new rules regarding this, imo the flags are enough.
