### ISSUE TITLE
Small troubles with syntaxic coloration in preprocessor defines

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#110]
# The problem

When a preprocessor identifier ending with digits is encountered, the token has 2 colors:
- preprocessor color until digits part
- number color on digit part
# Code samples
## First case

``` abl
&ANALYZE-SUSPEND _VERSION-NUMBER AB_v10r12 GUI
```
## Second case

``` abl
&Scoped-Define ENABLED-OBJECTS FL_WRK_DIR BT_BROWSE_DIR_WRK ~
FL_KEYWORDS_LIST BT_NEW_CARTO  RT_3 ~
RT_6 RT_10 RT_11 RT_12 
```
# How it is rendered

![1](https://cloud.githubusercontent.com/assets/7109720/19836499/8d080aa0-9ea2-11e6-822c-17f94bc3c8b4.PNG)
# You turn now...

Thanks for all!

Mega-big-best reagrds

**Comment by jcaillon** [comment]
Can't easily handle this case for now as I use the UDL system of Npp, not worth fixing
