### ISSUE TITLE
Show &ANALYZE-SUSPEND / &ANALYZE-RESUME inconsistencies on file opening

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#112]
Considering a file like this, 3P should display a notification to inform the user.
Please note 3P performs the check when you ask to insert a procedure ou function.

``` abl
&IF DEFINED(EXCLUDE-BuildEntitiesList) = 0 &THEN

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE BuildEntitiesList Procedure
PROCEDURE AnalyzeKeywords :
    RETURN "".
END PROCEDURE.


&IF DEFINED(EXCLUDE-LoadKeywordsList) = 0 &THEN

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE LoadKeywordsList Procedure
PROCEDURE LoadKeywordsList :
    RETURN "".
END PROCEDURE.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME

&ENDIF
```

Thanks for considering this ticket.
May regards.

**Comment by jcaillon** [comment]
It also checks that when you save the file. This makes more sense because the main goal of this warning is to prevent the user to make __modifications in 3P__ that would make the file unreadable by the APPBUILDER.
