### ISSUE TITLE
Extend function prototype synchronisation to procedures and UIB sections

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#113]
It may be usefull to 3P to detect and correct synchronization between procedure names and AppBuilder internal &xxx lines.
For instance, in the following sample code, all AppBuilder are false (probably due to wrong copy/paste) and detection / correction seems easy to do.
See also: it can be also extended to functions and events.

``` abl
&IF DEFINED(EXCLUDE-BuildEntitiesList) = 0 &THEN

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _PROCEDURE BuildEntitiesList Procedure
PROCEDURE AnalyzeKeywords :
    RETURN "".
END PROCEDURE.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME

&ENDIF
```

As always, thanks a lot.
Regards

**Comment by jcaillon** [comment]
This kind of error should never happen since there is a feature to create a new procedure/function
