### ISSUE TITLE
Procedure deletion partially deletes EXTERNAL procedures

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#114]
Considering this piece of code:

``` abl
/* -------------------------------------------------------------------------- */
/* EXTERNAL API                                                               */
/* -------------------------------------------------------------------------- */
PROCEDURE Sleep EXTERNAL "KERNEL32":
    DEFINE INPUT  PARAMETER lMilliseconds   AS LONG.
END PROCEDURE.
```

"Delete existing internal procedure" feature will:
- propose to delete procedure "Sleep" (not that bad but 3P should mind this is an external procedure)
- only remove the first line, making the file erroneous :(

``` abl
/* -------------------------------------------------------------------------- */
/* EXTERNAL API                                                               */
/* -------------------------------------------------------------------------- */
    DEFINE INPUT  PARAMETER lMilliseconds   AS LONG.
END PROCEDURE.
```

Thanks for fixing.
Regards.

**Comment by jcaillon** [comment]
Thx, there was a mistake in the code suppression, I was only deleting from the beggining of the procedure to the end of the procedure declaration statement! It would only work well when the procedure was surrounded by an appbuilder preprocessed block.
