### ISSUE TITLE
Compilation error meta information not inserted at the correct line

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#115]
See in following screen capture:
  * one ```PUT``` instruction is splitted over multiple lines
  * there is an error in the statement usage
  * error is not at the firt line
  * 3P tells error is at the first line

![1](https://cloud.githubusercontent.com/assets/7109720/19890948/faf0292a-a03d-11e6-97d5-15ad34c03877.png)

**Comment by jcaillon** [comment]
3P is only displaying information relayed by the Progress compilator. Said compilator places the error on the line of the beggining of the statement. But reading the error message gives you more information.
