### ISSUE TITLE
Display troubles with file explorer

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#116]
What I did:
1. show the "file explorer" panel with about 20 displayed files
2. undock the panel
3. scroll down the list (about 10 files)
4. double click on the panel title so that it will be docked again

Tada....
![1](https://cloud.githubusercontent.com/assets/7109720/19897848/0e75f008-a05a-11e6-97d0-c0a94bfebbda.png)

Thanks for fixing.
Regards

**Comment by jcaillon** [comment]
This kind of glitches will be fixed in the next version as I will no longer use the ObjectListView library but a custom code to display lists and tree view
