### ISSUE TITLE
Auto-completion popup shows when it shouldn't

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#117]
Hi dear,

# What's up?
This time, the topic is "auto-completion popup shows in a non terminated multiline comment and in single line comment".

# Case 1
Somewhere in your code (not in a comment and not in a string), type this:
```abl
/* --- xx
```
--> you will show the auto-completion list for XX, proposing XML-XREF
Please note that if the comment is closed, no auto-completion list appears.

# Case 2
Somewhere in your code (not in a comment and not in a string), type this:
```abl
// --- xx
```
--> you will show the auto-completion list for XX, proposing XML-XREF

# What's next?
You turn now.
Thanks for fixing.

Best regards,

**Comment by jcaillon** [comment]
Only happends when the carret is on the last line, pretty minor..
