### ISSUE TITLE
Default value for INTEGER not displayed in tooltip

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#119]
The below pictures show default values for CHARACTER fields, but not for INTEGER ones.
Maybe the same behavior happens with INT64, DATE, DATETIME, DATETIME-TZ and other types.

![1](https://cloud.githubusercontent.com/assets/7109720/19923190/92d36e3e-a0e6-11e6-8a6e-b4c12fafe8ab.png)

As always, thanks for fixing.

**Comment by jcaillon** [comment]
done
