### ISSUE TITLE
Add a vertical scroll-bar in tooltips

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#12]
Hi,

When hovering a procedure name that uses 18 parameters, the tooltip information is truncated and some sections are missing.
It would be nice to add a vertical scrollbar.

Thanks

Regards,
C.CLEAUD

**Comment by ccleaud** [comment]
Same problem occurs when hovering the COMPILE keyword

**Comment by jcaillon** [comment]
**Ok**

Corrected in the next release (v1.0.1)
