### ISSUE TITLE
"File explorer" panel wongly repositionned when changing screen size

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#121]
I was unplugging my VGA cable from my laptop so Windows changed resolution to fit the new built-in screen.
I could see following problem: 
![1](https://cloud.githubusercontent.com/assets/7109720/20010863/f815700c-a2a9-11e6-9b3a-91b9d56482cd.png)
Thanks for fixing.
Regards

**Comment by jcaillon** [comment]
The plugin didn't receive the windows message indicating that Npp's windows has been resized. The cost to fix (with a workaround) is too big for the small problem it causes.
-> clicking on the windows, moving it or resizing it will replace the explorer.
