### ISSUE TITLE
Syntaxic coloration problem

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#122]
How to reproduce:

1. open an OpenEdge source file
2. split it over 2 view
3. open a simple text document in left view
4. open a simple text document in right view 
5. give focus to text document in right view
6. give focus to OpenEdge document in left view
7. close simple text document in right view using mouse middle click

==> N++ gives focus to OpenEdge document in right view but syntaxic coloration is wrong

**Comment by jcaillon** [comment]
Actually it __doesn't__ give focus to the document on the right -> hence why the coloration is not applied.
But the colors are back when you click on view. This is acceptable to me
