### ISSUE TITLE
Function / procedure insertion accepts special characters like spaces in target entity name

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#123]
A little bit stupid, I agree.
But 3P let me create an internal function named "Is   Main   Session".

```abl
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _FUNCTION Is   Main   Session Procedure
FUNCTION Is   Main   Session RETURNS LOGICAL PRIVATE
  ( /* parameter-definitions */ ) :
/*------------------------------------------------------------------------------
  Summary    :     
  Parameters : <none>
  Returns    : 
  Remarks    :       
------------------------------------------------------------------------------*/

    DEFINE VARIABLE retVal AS LOGICAL NO-UNDO.

    

    RETURN retVal.

END FUNCTION.
```

More over, this caused 3P to mis-detect that function:
![1](https://cloud.githubusercontent.com/assets/7109720/20031445/eae87824-a377-11e6-96ce-3944796d4a90.png)

Other than that, 3P isn't able to synchronize function prototypes in such case.
It created new dummy sessions and break the code.
Need to revert my changes.

**Comment by jcaillon** [comment]
done, the generate code menu is now "fool safe"
