### ISSUE TITLE
Missing &IF DEFINED / &ENDIF around function declaration created using 3P

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#124]
## Case 1: creating a function using AppBuilder
Generated code for function declaration is:
```abl
&IF DEFINED(EXCLUDE-GetParam) = 0 &THEN

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _FUNCTION-FORWARD GetParam Procedure
FUNCTION GetParam RETURNS CHARACTER PRIVATE
  ( ipcParamName AS CHARACTER ) FORWARD.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME

&ENDIF
```

## Case 2: creating a function using 3P
Generated code for function declaration is:
```abl
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _FUNCTION-FORWARD IsMainSession Procedure
FUNCTION IsMainSession RETURNS LOGICAL PRIVATE
  ( /* parameter-definitions */ ) FORWARD.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME
```

Thanks for all.

**Comment by jcaillon** [comment]
That's intended, the code 

```
&IF DEFINED(EXCLUDE-GetParam) = 0 &THEN
```

is useless most of the time. Plus if you open the program in the appbuilder and save it, it will generate the `&ANALYZE-SUSPEND` block but not the `&IF` block. So opening your file in the appbuilder will not modify it.
