### ISSUE TITLE
Entities names in code explorer are not fully displayed

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#125]
Progress ABL allows to use some special characters in entity names, like '-', '%' and some other.
But they are excluded when displayed in code explorer.

![1](https://cloud.githubusercontent.com/assets/7109720/20031557/e597457e-a379-11e6-835e-f6a1d56f1c0e.png)

Moreover, any character after '%' is not displayed.
Thanks for fixing.

**Comment by jcaillon** [comment]
`-` is taken into account correctly. `%` however... In a variable or procedure name??? I can't find anything in the progress documentation but it feels like an extremly bad practice that I wouldn't want to promote by considering it.
