### ISSUE TITLE
** FATAL PANIC ** [RARE] - Notepad++ crashed right after syntax check (SHIFT + F1)

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#127]
Right after performing syntax check (with errors), details about error are inserted between lines of code.
Just at this moment: crash due to memory violation.

My first steps in analysis came to conclude of a problem in scintilla library (scilexer.dll).
**The question is: "Is the library simply bugged or do commands sent to scintilla are sometimes erroneous?"**

What I got:
![1](https://cloud.githubusercontent.com/assets/7109720/20031734/83633a4a-a37c-11e6-8129-df8b3d7bba6e.png)

What memory vialoation is related to:
![2](https://cloud.githubusercontent.com/assets/7109720/20031735/84f5e9b6-a37c-11e6-9a22-4477af4271dc.png)
Please note I don't have the thread ID.

Crash dump manually generated:
[NppDump.zip](https://github.com/jcaillon/3P/files/573339/NppDump.zip)

Thanks for all.
Regards.
Good luck.

**Comment by jcaillon** [comment]
Hi, try to update your version of notepad++, I never encountered this bug in 6 months of intensive use.
