### ISSUE TITLE
Wrong abbreviation detections with pre-processor keywords

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#128]
`&SCOPED` is an abbreviated form of `&SCOPED-DEFINE`.
So, `&SCOPED` should not be accepted when typing and should be automatically replaced by `&SCOPED-DEFINE`.

I guess the same behavior occurs with `&GLOB`, `&GLOBAL` and `&GLOBAL-DEFINE`.

Thanks for fixing.
Regards.

**Comment by ccleaud** [comment]
Please let me know if you want the keywords list with abbreviated forms.

**Comment by jcaillon** [comment]
done thx
