### ISSUE TITLE
Craps remain in 3P temporary directory even after Notepad++ is closed

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#130]
When exiting Notepad++, not all temporary directories / files created in "%TEMP%\3P" in current session are deleted.
Event if %TEMP% is dedicated to temporary files, not deleteing them is dirty.

As you can see in the below screenshot, no Notepad++ is running but there are still directories in 3P temporary directory.
![1](https://cloud.githubusercontent.com/assets/7109720/20039933/d190e060-a44d-11e6-8c06-4d4c8c057a62.png)

Thanks for taking this into account.
Regards

**Comment by jcaillon** [comment]
Already done, but I added the suppression of this folder on restart if it wasn't done well in the first place.
