### ISSUE TITLE
Variable type not well recognized

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#132]
Following code is valid in ABL:
```abl
DEF VAR i AS i NO-UNDO.  /* INTEGER */
DEF VAR c AS c NO-UNDO.  /* CHARACTER */
DEF VAR m AS m NO-UNDO.  /* MEMPTR */
```

3P doesn't deal with it very well:
![1](https://cloud.githubusercontent.com/assets/7109720/20040836/2bdef410-a45f-11e6-84be-d3ddbf287187.png)

Thanks for fixing!
Best regards.

**Comment by jcaillon** [comment]
According to Progress's own documentation, the minimum abbreviation for CHARACTER (for instance) is CHAR : 
![image](https://cloud.githubusercontent.com/assets/11553075/21499726/9fb7550c-cc38-11e6-952b-4bd7d784a9a2.png)

Sorry, won't fix this
