### ISSUE TITLE
3P plugin loaded twice in Notepad++

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#133]
I don't know why or how.

According to the screenshot, 3p.dll is loaded twice in Notepad++ address space:
![9](https://cloud.githubusercontent.com/assets/7109720/20042558/76300924-a47c-11e6-885d-aaa391f755cb.png)

Loading this DLL once would speed up Notepad++ startup.
Thanks for considering this.

**Comment by jcaillon** [comment]
Sorry, not the case on my hand; and I don't load it twice, i fact I don't even have anything to say concerning the load of my .dll since it's purely handled by Npp

![image](https://cloud.githubusercontent.com/assets/11553075/21499595/9b86f02e-cc37-11e6-90bc-71e9215b17ef.png)
