### ISSUE TITLE
RUN mis-detected

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#134]
Target of a RUN instruction can be double-quoted.
Following pieces of code are valid in ABL but 3P mis detect them.

## Case 1
```abl
RUN "toto" IN THIS-PROCEDURE.
RETURN "".

PROCEDURE toto.
    MESSAGE "Hello" VIEW-AS ALERT-BOX INFORMATION.
END PROCEDURE.
```
![1](https://cloud.githubusercontent.com/assets/7109720/20050326/fb2d63c8-a4c8-11e6-88a9-811992c494e3.png)

## Case 2
```abl
RUN "toto".
RETURN "".

PROCEDURE toto.
    MESSAGE "Hello" VIEW-AS ALERT-BOX INFORMATION.
END PROCEDURE.
```
![2](https://cloud.githubusercontent.com/assets/7109720/20050342/12663664-a4c9-11e6-832a-22c059560f45.png)

As always, thanks for fixing.
Regards

**Comment by jcaillon** [comment]
Thx, fixed in the next release
