### ISSUE TITLE
how to find prowin32.exe

### ISSUE THREAD

**Issue by devjerome** [jcaillon/3P#139]

**Comment by devjerome** [comment]
im using win vista

**Comment by jcaillon** [comment]
Hi,

Go to your progress installation folder (I can't help you with that, it's usually C:\Program Files\progress or C:\progress or C:\Program Files (x86)\progress) and search for it : 

![image](https://cloud.githubusercontent.com/assets/11553075/20562322/3cdfb94e-b183-11e6-87cb-98691ec49a02.png)

It can be called prowin.exe if you are using the x64 version of progress.

**Comment by devjerome** [comment]
can you please full the image

**Comment by devjerome** [comment]
cannot find it
