### ISSUE TITLE
Freeze of Notepad++

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#14]
Hi,

Doing this causes Notepad++ to freeze:
1. open a Progress ABL program containing about 20+ procedures (just to make the code explorer pannel scrollable when undocked)
2. display the code explorer
3. ensure it is docked
3. undock it (via double-click)
4. scroll to the bottom
5. redock it (via double-click) --> rectangle is now full grey
6. undock it again then click in the panel
7. click in the Scintilla editor
8. Notepad++ is now frozen

Thanks for fixing this.

100% reproductible, ready to help you if needed.

Kind regards,
C.CLEAUD

**Comment by ccleaud** [comment]
Crash reproductble with Windows 7 x64 and Windows 8.1 x64.

**Comment by ccleaud** [comment]
Freeze reproductible on a fresh Notepad++ 6.8.8 copy, without any plugin except 3p.

**Comment by jcaillon** [comment]
This issue has been partially corrected in the above mentioned commit.

I'm closing it as it doesn't reflect the current bug.

Opened issue #42
