### ISSUE TITLE
3P - code explorer doesn't show event On *

### ISSUE THREAD

**Issue by jmacquart** [jcaillon/3P#140]
Hello Julien,
In 3P - code explorer ,
I can't see key event ON * OF machin
but i see normal key event like ON F10 OF machin.

PS:  C triste

Cordialement Bisous
JMM

**Comment by jcaillon** [comment]
Hi ;D

Indeed, I had no idea that 
```OpenEdge
ON * OF machin
```
was a valid syntax. That's why it isn't parsed correctly -> doesn't show up on the code explorer.

I'll try to consider this issue in the next release.

Thanks for using 3P, stay awesome!
