### ISSUE TITLE
cant find prowin32.exe

### ISSUE THREAD

**Issue by devjerome** [jcaillon/3P#141]

**Comment by ccleaud** [comment]
Are you using a 64-bits edition?
If so, the Progress Virtual Machine is named "prowin.exe".
Regards.

**Comment by jcaillon** [comment]
Can't help you more than I already did on this matter.
You can read this link : 

[https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/gsins/using-the-gui-interface.html](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/gsins/using-the-gui-interface.html)

**Comment by devjerome** [comment]
i dont have openedge progress installed

**Comment by jcaillon** [comment]
You can't use all the features of 3P without a proper installation of openedge Progress.
There are no work-arounds; sorry.

**Comment by devjerome** [comment]
could yo have a feature like cloud features

**Comment by devjerome** [comment]
without progress

**Comment by jcaillon** [comment]
Technically speaking yes. But first, I don't thing this would be within the bounds of a Progress license; and second I don't have time to invest in this solution for this particular project. This is A LOT of work...
Good luck to you.

**Comment by devjerome** [comment]
how do you install progress

**Comment by jcaillon** [comment]
Once again, this is not the openedge hotline...
[https://lmgtfy.com/?q=progress+support](https://lmgtfy.com/?q=progress+support)

I'm not sure if you are trolling intentionally or accidently but this will be my last answer to this thread.

I wish you good luck in your future work.
