### ISSUE TITLE
lowercase in version 1.7.1 is broken

### ISSUE THREAD

**Issue by TestUser013** [jcaillon/3P#143]
Hello,
I set "keyword auto case mode" to lowercased (2) and turn on "Enter" and "Tab" keys to accept suggestion. But words are put in uppercase.

**Comment by jcaillon** [comment]
Hello,

Damn, you are right, my bad. It will be fixed in the next version.
In the meantime, if you want to rollback to 1.7.0, you will probably need to delete the folder $PLUGINS/config/3P/Libraries

**Comment by TestUser013** [comment]
It's not a problem for me. I really like your plugin and I want that it be the best :)
Thanks for quick fix.

**Comment by jcaillon** [comment]
And I thank you very much for that! :+1:
