### ISSUE TITLE
Function prototype synchronizing

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#148]
Working code :

Function prototype :
![image](https://cloud.githubusercontent.com/assets/20086123/22819882/996f4538-ef74-11e6-9259-b2922ec3e3c9.png)

Function call :
![image](https://cloud.githubusercontent.com/assets/20086123/22819908/b686df78-ef74-11e6-9c4e-a4a43bbe820e.png)

Function definition :
![image](https://cloud.githubusercontent.com/assets/20086123/22819918/c30356c8-ef74-11e6-8546-89a91dad1888.png)

-> The function works without having the parameters explicitely defined in the definition. I guess the developper made a sacrifice to Progress God to make it work.

But after a "Check synthax" :
![image](https://cloud.githubusercontent.com/assets/20086123/22819965/ff65d2bc-ef74-11e6-9d51-689aa9bec6b3.png)

**Comment by jcaillon** [comment]
Hi, not sure to understand your issue; to me, your code seems incorrect?
Your prototype wasn't matching your function definition, 3P corrects it and the next check syntax obviously states that your function call is incorrect (wrong nb of parameters).

Either your code was not working BEFORE any modifications with 3P; or you are not showing an important part of the code that could explain a correct compilation before any modifications :)

**Comment by vvelletaz** [comment]
Hi,

We agree about the  source of the problem on 3P.
But the actual problem is that it isn't m'y code, and it was working before
any modification by 3P.
I guess Progress allows us to call a function with the parameters  only
specified in the prototype.

Le 13 févr. 2017 15:10, "Julien Caillon" <notifications@github.com> a
écrit :

**Comment by jcaillon** [comment]
Ok, so... after some tests, it seems that Progress allows to do the following : 

if you define a function prototype with parameters 

```OpenEdge
FUNCTION azdazazd RETURNS CHARACTER
  ( INPUT ipc_fuck AS CHARACTER ) FORWARD.
```

You can then define the function definition w/o the parameters but still using them... and it will work...

```OpenEdge
FUNCTION azdazazd RETURNS CHARACTER :
    RETURN "really??? = " + ipc_fuck.
END FUNCTION.
```

**HOWEVER**

This allows a RIDICULOUSLY bad practice... I will not modify 3P to take into account such behavior, please correct your source code so that the parameters are hold by the function definition as well :)
