### ISSUE TITLE
Not sure if deploying or cancelling the deployment

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#149]
![image](https://cloud.githubusercontent.com/assets/20086123/22930342/0326bfe4-f2c0-11e6-932a-49d5aaa97aa9.png)

![image](https://cloud.githubusercontent.com/assets/20086123/22930389/3f9b8ae0-f2c0-11e6-806f-d76cf2c353a4.png)

**Comment by jcaillon** [comment]
nice one :p thx for reporting this
