### ISSUE TITLE
Funtion list settings destroyed if plugin installed

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#15]
Thanks for fixing.
Best and kind regards
C.CLEAUD

**Comment by ccleaud** [comment]
Hi,

This is because 3P changes Progress ABL files (.p, .w, .i, .cls) association to "OpenEdgeABL" User Defined Language.
However, the function list XML configuration is linked to language "Progress ABL".

**Comment by ccleaud** [comment]
It would be nice

**Comment by ccleaud** [comment]
I don't know if this is fixable.
Maybe using your own lexer without UDL is the right way...

**Comment by jcaillon** [comment]
**Oh good catch!**

Well, this is a good news!
Yeah, i will implement a custom lexer for the first *stable release*.
For now, i consider this issue closed since there is no way that a random user could encounter this bug. I advice to start with a clean notepad++ installation before installing 3P.

**Comment by ccleaud** [comment]
Should I understand I'm a random user? ;)
BTW I used a new, fresh and clean N++ installation.
