### ISSUE TITLE
System tables : autocompletion

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#152]
![image](https://cloud.githubusercontent.com/assets/20086123/23252659/eb294d28-f9b1-11e6-883f-2260dc2ba669.png)

Would it be possible to get some autocompletion on system tables ?

Thanks!

**Comment by jcaillon** [comment]
The option will be available in the environment page.
Below is an example configuration to fetch all user tables + the system tables that interest you : 

![image](https://user-images.githubusercontent.com/11553075/36218597-3a50ac4a-11b5-11e8-981c-c9d927f686da.png)
