### ISSUE TITLE
DataBase Connection per method

### ISSUE THREAD

**Issue by Qomaa** [jcaillon/3P#154]
Hi, first of all: This is a great plug in, thanks!

I have the issue that I connect my databases via a routine. I don't use the environment options "List of databases" or "Extra connection". But when I connect my databases I can't use them. It says, that no database is connected. Have someone an explanation?

Thanks!

**Comment by jcaillon** [comment]
Hello,

Thank you for the feedback;

Concerning your issue, to my understanding :

- you have a .p file in which you pragmatically connect to a database `CONNECT -db...`
- you have no databases references in 3P (in the set environment page)
- you try to get the database structure from the environment page and it says that no db are connected

Is that it?

If that's the case, I see two options : 

- first, set the database .pf connection file or the extra connection field in the environment page
- second option; I will add a new feature that allows the user to set a progress program to be run BEFORE any progress actions. This will allow you to directly use your connection program, it will be executed before each compilation/check syntax/get database structure and so on...

Sounds good to you?

**Comment by Qomaa** [comment]
Thank you for your answer!

You understand it right. I connect to multiple databases based on a certain logic in the .p file.  But after I run the .p file (separatly, as "stand alone"), the following programs don't recognize the connected databases as it is an "environment restart".

Your second option is exactly what I'm looking for!

**Comment by jcaillon** [comment]
Alright, I actually already a request for this kind of feature so I'll try to ship it in the next beta release.
