### ISSUE TITLE
CTRL+i keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#16]
Hi,

CTRL+i keyboard shortcut gives focus to filter text-box in the "File Explorer" panel but does not format the document.
Same bahavior even if the action isselected from the plugin --> 3P --> Format document menu.

Thanks for fixing.

Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
Yeah, my bad. This should point to a "not implemented" message.

This feature will be available soon, it should have been disabled in release v1.0.0.0

Closing the issue
