### ISSUE TITLE
Function synchronizing

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#160]
### Description of the Issue

Function synchronizing
### Steps to Reproduce the Issue

1. Having functions defined in an include

### Expected Behavior

I don't know, but not what happened
### Actual Behavior

Check out the screen shots
### Debug Information

V1.7.4 (beta)

Step 1 : I'm chilling on my program
![image](https://cloud.githubusercontent.com/assets/20086123/24742484/b91f0f4c-1aaa-11e7-95fe-fdbe98ee626b.png)
Step 2 : I use the "Check synthax" combo
![image](https://cloud.githubusercontent.com/assets/20086123/24742528/e90bd6ea-1aaa-11e7-921e-91d297d3c8ab.png)
-> The code is wrecked
Step 3 :
I press Ctrl + Z to undo the mess. Then, I try to tell to 3P that I don't want the auto-update anymore :+1: 
![image](https://cloud.githubusercontent.com/assets/20086123/24742581/333159d4-1aab-11e7-95a7-1b87a65164a2.png)
But... the next time I check the synthax, the same thing happens :(

**Comment by jcaillon** [comment]
Thanks for reporting the bug. I'll correct it for the next version.
Meanwhile, you can disable automatic updates of function protoypes in the options (you can still update them manually with ALT+S by default)
