### ISSUE TITLE
1.7.4 BETA: Error when checking syntax or compile

### ISSUE THREAD

**Issue by Qomaa** [jcaillon/3P#161]
### Description of the Issue
I updated from 3P 1.7.0 to 1.7.4 BETA. Now, an error occurs when I "Check syntax", "Compile", ... (see debug info). After the error, nothing happens when I click "Check syntax", "Compile", ... until I restart Notepad++, but then again the error occurs.
When I switch back to 1.7.0 it works as usual.

### Debug Information
3P: 1.7.4 BETA 32-bit
Notepad++ 7.3.2 32-Bit

WHAT : Error in : Check syntax : Die Länge darf nicht kleiner als 0 (null) sein. (translates to "The length must not be smaller than 0 (null).")
Parametername: length
WHEN : 07.04.2017 08:06:08
WHERE : System.String.Substring(), line 0
DETAILS : 
    System.ArgumentOutOfRangeException: Die Länge darf nicht kleiner als 0 (null) sein.
    Parametername: length
    bei System.String.Substring(Int32 startIndex, Int32 length)
    bei _3PA.MainFeatures.Pro.ProGenerateCode.AddPrototypes(StringBuilder& outputMessage, ParsedImplementation function) in c:\projects\3p\3PA\MainFeatures\Pro\ProGenerateCode.cs:Zeile 343.
    bei _3PA.MainFeatures.Pro.ProGenerateCode.UpdateFunctionPrototypes(Boolean silent) in c:\projects\3p\3PA\MainFeatures\Pro\ProGenerateCode.cs:Zeile 218.
    bei _3PA.MainFeatures.Pro.ProGenerateCode.UpdateFunctionPrototypesIfNeeded(Boolean silent) in c:\projects\3p\3PA\MainFeatures\Pro\ProGenerateCode.cs:Zeile 184.
    bei _3PA.MainFeatures.Pro.ProMisc.StartProgressExec(ExecutionType executionType, Action`1 execSetter) in c:\projects\3p\3PA\MainFeatures\Pro\ProMisc.cs:Zeile 358.
    bei _3PA.MainFeatures.AppliMenu.<.ctor>b__5d(YamuiMenuItem item) in c:\projects\3p\3PA\MainFeatures\AppliMenu.cs:Zeile 295.
    bei _3PA.MainFeatures.AppliMenu.<ShowMenu>b__1(YamuiMenuItem item) in c:\projects\3p\3PA\MainFeatures\AppliMenu.cs:Zeile 110.

**Comment by jcaillon** [comment]
Hi @Qomaa ,

Thanks for reporting the bug.
It would be very helpful if you could send me the progress program that causes the bug (I understand if you can't!).

In the meantime, if you want to continue using the beta version, you can disable the autoupdate of prototypes here : 
![image](https://cloud.githubusercontent.com/assets/11553075/24795098/73d82c3c-1b88-11e7-8903-d9aec08d83bf.png)

**Comment by Qomaa** [comment]
Hi jcaillon,

The autoupdate of prototypes option were disabled all the time. I can't send you the program, but I have done some tests and I think I could isolate the bug.

Try to reproduce like this:

In the .p-file:
`{myinc.i}`

In the .I-file:
```
FUNCTION MyFunc RETURN INTEGER FORWARD.

FUNCTION MyFunc RETURN INTEGER:
  RETURN 0.
END FUNCTION.
```

then execute "Check syntax".

Let me know if you need more info!

**Comment by jcaillon** [comment]
Yes perfect, I can reproduce it, thank you very much for the help!
