### ISSUE TITLE
1.7.4 Beta : No autocompletion when typing buffers

### ISSUE THREAD

**Issue by ggouttesolard** [jcaillon/3P#162]
### Description of the Issue
There is no autocompletion when you type a buffer. Furthermore, when you point on a buffer, the fields of the table pointed by the buffer are not displayed.

### Steps to Reproduce the Issue
Typing a buffer : 
![image](https://cloud.githubusercontent.com/assets/23432181/24803304/1b9c96ca-1bab-11e7-92fb-6ad16372a1ea.png)

Or try to have a look on the fields of the buffer : 
![capture](https://cloud.githubusercontent.com/assets/23432181/24803322/2dcfbbce-1bab-11e7-94f4-9fa240c9910f.PNG)

### Expected Behavior
When typing a buffer :
![32f2d5f4](https://cloud.githubusercontent.com/assets/23432181/24803851/c93b4e4c-1bac-11e7-92aa-59e9cf9a151b.PNG)

And when pointing on the buffer : 
![3c681565](https://cloud.githubusercontent.com/assets/23432181/24803854/cc92cb06-1bac-11e7-94fe-c7af8d8a1b7b.PNG)

### Debug Information
3P version ; 1.7.4 Beta
N++ version : 7.3.2

**Comment by jcaillon** [comment]
Oh my bad! 
Indeed, I have totally changed the inner logic of the autocompletion and I forgot about buffers; they need to have the same "children" as the table they reference.
I will correct it for the next release, thanks for reporting :)
