### ISSUE TITLE
Code Explorer: Too much information

### ISSUE THREAD

**Issue by Qomaa** [jcaillon/3P#163]
### Description of the Issue
Since 1.7.4 Beta the information in Code Explorer is overwhelming.  It always displays "extern" info, but I can't find the button to disable it. In 1.7.0 there was such a button. Have the button been moved?
![1](https://cloud.githubusercontent.com/assets/26574474/24895731/3bf575d8-1e92-11e7-94b2-9b70d812d602.PNG)

**Comment by jcaillon** [comment]
Hi @Qomaa,

Yes indeed, I actually removed this option. But I understand your issue, if you have a lot of include files it can become a pain to navigate through the code explorer. I'll add back the old "external" button, which will now be labelled "Show included items" (or something like that).

**Comment by jcaillon** [comment]
Hi, 

If you want to test the modification (and also your previous issues), you can download the latest build for x86 [here](https://ci.appveyor.com/api/buildjobs/49rqueh2t2hnk0f1/artifacts/Releases%2F3P.zip)

br
