### ISSUE TITLE
Search window inactive when CRTL+F

### ISSUE THREAD

**Issue by Qomaa** [jcaillon/3P#164]
### Description of the Issue
When the text cursor is on a word and I press CRTL+F for searching, the search window is immediately set to inactive and the text editor to active. 

### Steps to Reproduce the Issue
1. Create new file
2. Set text cursor on a word (don't select whole word)
3. Press CTRL-F for search

### Expected Behavior
Search window gets activated, so i can press Enter to search the word.

### Actual Behavior
Text editor gets activated. When pressing Enter, the text/code is edited.

3P version downlaoded here: https://ci.appveyor.com/api/buildjobs/49rqueh2t2hnk0f1/artifacts/Releases%2F3P.zip

**Comment by jcaillon** [comment]
Thank you for reporting the bug, it wil be fixed in the next version!
