### ISSUE TITLE
Incomplete procedure name in Code Explorer

### ISSUE THREAD

**Issue by Qomaa** [jcaillon/3P#165]
### Description of the Issue
The procedure names in the Code Explorer are incomplete when naming with SCOPEs (see screenshot). And I can't "Goto definition" to such name procedures.

### Steps to Reproduce the Issue
```
&SCOPED-DEFINE  SCO  MYSCOPE
PROCEDURE {&SCO}-MyProcedureName:
END PROCEDURE.
```

### Expected Behavior
Procedure name in Code Explorer: MYSCOPE-MyProcedureName

### Actual Behavior
Procedure name in Code Explorer: MYSCOPE

### Screenshot
![1](https://cloud.githubusercontent.com/assets/26574474/25419631/19f8ff0e-2a54-11e7-8f4e-e8c79e8c702c.PNG)

Used 3P-Version: https://ci.appveyor.com/api/buildjobs/49rqueh2t2hnk0f1/artifacts/Releases%2F3P.zip

**Comment by jcaillon** [comment]
Hi, yes indeed, they are currently processed as 2 words separated by a symbol instead of being just 1 word. I'll correct it in the next version
