### ISSUE TITLE
Closing "File Explorer" panel when undocked doesn't update the toolbar button status

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#17]
Hi,

Very minor bug.

1. show the file explorer panel (the vertical flipped "3P" tolbar button is highlighted)
2. undock the file explorer panel
3. close it using the window close button
4. the vertical flipped "3P" tolbar button is still highlighted

Please note: this does not happen with the "code explorer" panel.

Can you fix this, please?
Better than kind regards :)
C.CLEAUD

**Comment by jcaillon** [comment]
**Ok,**

Corrected in the next release (v1.0.1)

**Comment by ccleaud** [comment]
I think it was the harder bug to correct.
