### ISSUE TITLE
Enhancement Idea: PS:escript support

### ISSUE THREAD

**Issue by ray73864** [jcaillon/3P#170]
We use ps:escript at work (would love to not have to, but we are so far into using it -- have been using it for 8yrs now) that it's not going anywhere anytime soon.

ps:escript adds a few things to the AppBuilder, 2 of which are the 'ps:escript Explorer' and 'ps:escript Editor', the explorer allows you to add webobjects to the PSE database, add services, set up links, etc... I can live without this one as I just bring up the psetools web page to do those things as the Explorer has a horrible interface.

ps:escript Editor brings up a notepad like editor where you can open HTML/JS/CSS/etc... files from the PSE database and save them back to the PSE database.

The links for ps:escript are few and far these days, but: 
 - http://www.trtiimi.fi/escript/escript_framework.ppt
 - http://www.trtiimi.fi/escript/pseScript.doc

**Comment by jcaillon** [comment]
Hi,

Thanks for the feedback. However, this is an extremely specific request which will probably only be useful to a handful of people. It's not that I don't want to consider this ticket, but I have a very long list of features I want to implement and this one is doomed to stay on the bottom of said list... But i would definetely consider a pull request :p

br
