### ISSUE TITLE
Indentation correction issue

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#171]
### Description of the Issue

The indentation correction has some issues.

### Steps to Reproduce the Issue

1. Use the feature "Correct document indentation"
2. Be amazed by the indentation correction, but still a bit confused with the result :

![image](https://user-images.githubusercontent.com/20086123/26981471-954d56ce-4d35-11e7-8d9f-7775dc70c4c0.png)

### Expected Behavior

Something else I  guess.

**Comment by jcaillon** [comment]
code snippet to reproduce
```
IF i_typcommi = "ADM" THEN DO:

END.
ELSE IF i_typcommi = "PEN" THEN DO:
    
    END.
```

**Comment by vvelletaz** [comment]
Thanks !

Le 9 janv. 2018 11:12 PM, "Julien Caillon" <notifications@github.com> a
écrit :
