### ISSUE TITLE
Keyboard shortcuts configuration is not respected

### ISSUE THREAD

**Issue by pietmapa** [jcaillon/3P#172]
### Description of the Issue

* 1
Go to 3P menu Options Shortcuts;
Clear all shortcuts by pressing the bin buttons on the right;
Go to the menu Options Others;
Return to the menu Options Shortcuts;
Notice that several shortcuts have reappeared.
**It's not possible to clear all 3P shortcuts** this way and I consider this a bug.

* 2
In the Windows AppData settings.xml for 3P, you can clear the shortcuts by manually clearing the Value tags like so:
`     <DicoShortCuts> `
       `<ShortCuts> `
         `<Key>Open_4GL_help</Key> `
         `<Value></Value> `
      `</ShortCuts> `
When you now start up Notepad++ and 3P, you'll notice that all shortcuts have successfully been cleared - Check the 3P menu Options Shotcuts.
When you close Notepad++, 3P will reduce the settings.xml configuration to this:
    `<DicoShortCuts /> `
When you start up Notepad++ once again, 3P will misinterpret its own settings.xml and automatically activate all the default keyboard shortcuts instead of leaving them cleared, which brings me back to point 1 : It's not possible to clear all shortcuts.

* 3
Ctrl+K makes 3P add  "`&ANALYZE-SUSPEND  `" to a selected text, while I want it to perform a Single Line Comment action, which is the default Notepad++ behavior.
I have found no way to clear this 3P Ctrl+K -shortcut. Is it possible that it's missing?

### Steps to Reproduce the Issue
See Description

### Expected Behavior
Control over all 3P keyboard shortcuts.

### Actual Behavior
Unexpectedly reappearing default configurations and missing settings.

### Debug Information
3P v1.7.0

Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : 3P.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by jcaillon** [comment]
Hello,

The 1 and 2 are corrected in the latest version (beta), they were indeed bugs of the 1.7 stable version. You can get the beta version by checking "i want the beta version" in the options > update

As for number 3, CTRL+K is a notepad++ shortcut that toggle the single line comment. It appends &ANALYZE-SUSPEND" because i defined it as a line comment in the User Defined Language in order to correctly display the syntax color. You can disable it through the notepad++ shortcut menu :)

++
