### ISSUE TITLE
Compilation error hidden

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#173]
### Description of the Issue

A program failed to compile, but 3P lies about it and pretends everything is OK !

The message I get from the beta version - v1.7.4 - when i'm compiling :

![image](https://user-images.githubusercontent.com/20086123/27389045-946dd85c-569d-11e7-9a36-079e1360a12f.png)

The message I get from v1.7.0 :

![image](https://user-images.githubusercontent.com/20086123/27389150-dd5322ac-569d-11e7-9e32-476afb044f6d.png)

![image](https://user-images.githubusercontent.com/20086123/27389162-e7e11544-569d-11e7-8eae-67a8d49041c4.png)

**Comment by jcaillon** [comment]
fixed!
