### ISSUE TITLE
Disabling 3P Autocomplete should enable Notepad++ Autocompletion.

### ISSUE THREAD

**Issue by amaneja** [jcaillon/3P#174]
### Description of the Issue

When disabling the 3P Autocompletion, it's unable to get back the Notepad++ default Autocompletion which is created from the words from the current program file.
### Steps to Reproduce the Issue

1. Disable the Auto-Completion of 3P
2. Try Ctrl + Space to fetch default Notepad++ Auto-Completion
3.  An auto-completion list will snap for fraction of a second and go away.

### Expected Behavior

Ideally, if someone does not need 3P autocompletion, it should switch back to Notepad++'s Auto-Completion

### Actual Behavior

An auto-completion list snaps for fraction of a second and goes away

### Debug Information

3P Version 1.7.0

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : 3P.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by jcaillon** [comment]
Hi @amaneja ,

Thanks for the bug report.
Indeed, this was an issue in v1.7.0. Notepad++ doesn't allow to disable the default autocompletion programatically so i had to force it to hide. And I continue to do so even if you disable the autocompletion of 3P. This is fixed in the latest beta where 3P can also replace the default notepad++ autocompletion.

A question though : do you really want to disable the autocompletion of 3P in progress files? And if yes, why? x)

Best regards

**Comment by amaneja** [comment]
Hi Julien,

I really appreciate you getting back to me on this.

As for the bug, I don't like the fact that the autocompletion always inputs
the characters as CAPS. And I kind of like the Notepad++'s drop down. It's
way simpler. The 3P's looks very complex and irrelevant at times.

My suggestion is to have 2 drop-downs, 3P and traditional npp's dropdown
(if 3P can't enable it, maybe can develop one similar to it, using same
libraries)

Also, I found no options to make the keywords lowercase when it
autocompletes OR when I press space after I enter a Keyword.

The organisation where I works uppercase keywords are not allowed and I
have to manually select the text and use the lowercase feature of
notepad++. Im thuis process sometimes the camel case for my function names
and procedure names is also modified and it's quite annoying. For now, I
have uninstalled 3P. But I will re-install once the drop-down is functional.

Hoping to get these things included. Let me know if any help is needed. I'd
love to be a part of this little advancement.

Regards,
Aman

On Jul 21, 2017 10:49 PM, "Julien Caillon" <notifications@github.com> wrote:

Hi @amaneja <https://github.com/amaneja> ,

Thanks for the bug report.
Indeed, this was an issue in v1.7.0. Notepad++ doesn't allow to disable the
default autocompletion programatically so i had to force it to hide. And I
continue to do so even if you disable the autocompletion of 3P. This is
fixed in the latest beta where 3P can also replace the default notepad++
autocompletion.

A question though : do you really want to disable the autocompletion of 3P
in progress files? And if yes, why? x)

Best regards

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jcaillon/3P/issues/174#issuecomment-317060503>, or mute
the thread

**Comment by jcaillon** [comment]
No problem.

I don't remember if the latest stable version (1.7.0) has the option to autocomplete in lowercase but the latest beta can do it (the last 2 options shown here should be set to 2 for lowercase) :

![image](https://user-images.githubusercontent.com/11553075/28498366-f15b9b78-6f9b-11e7-990a-ac8c32d98fa5.png)
 
Are you aware that 3P also autocompletes the DB.TABLE.FIELD ?

**Comment by amaneja** [comment]
Hi Julien,

I'll see if that fixed my issue. Sorry I couldn't give much time in these
days. Thanks for your efforts.

Thanks
Aman S. Aneja
