### ISSUE TITLE
Notepad ++ screen resize

### ISSUE THREAD

**Issue by kolonuk** [jcaillon/3P#175]
### Description of the Issue
I assume this is just a 3P issue, as other toolbars/work areas in Notepad++ still function fine...  Also it's not urgent or important or breaking anything

With just the 3P code explorer showing on the right, resizing the Notepad++ window using the right hand resize area of the Notepad++ window causes the 3P Code Explorer to "stay where it is", and the Notepad++ window has an empty grey area.

Before:![image](https://user-images.githubusercontent.com/5969835/28460869-f601484e-6e0b-11e7-81bd-1f2c8bd900f0.png)

After:![image](https://user-images.githubusercontent.com/5969835/28460864-eab0fad4-6e0b-11e7-93d3-4af0ba8e15c0.png)

Using the bottom-right 4 direction resize area is fine (although 3P Code Explorer is slow to catch up sometimes), and dragging the Notepad++ window title bar around also fixes this.

I am using the latest version of Notepad++ and 3P (as per websites).

I haven't tried anything other than re-installing Ntoepad++ and 3P

### Steps to Reproduce the Issue
1. Install Notepad++
2. Install 3P plugin
3. Drag right hand "resize area" of Notepad++ window to resize left and right

### Expected Behaviour
3P Code Explorer side panel to be shown within the Notepad++ window regardless of sizing method or window position on the desktop.

### Actual Behaviour
3P Code Explorer side panel stays where it is if Notepad++ is resized left or right, using the right hand resize area.

### Debug Information
Windows 10 - I do have the latest Creators update installed!
3P Version: 1.7.0 (installed via Notepad++ plugins)

Debug menu option:
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : 3P.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by jcaillon** [comment]
Hi @kolonuk,

Thanks for the bug report. I was aware of this QOL issue, Ill try to do something about it... someday ^^
This is due to the "funny" way I implemented the side panels -> all this to avoid a more important bug caused by the use of winforms as panels in notepad++...

Can't promise a fix in the next version, but i keep it in mind

Regards

**Comment by kolonuk** [comment]
I kinda guessed that it was doing something different.  Like I said, it's not breaking anything, and this is the first time I've noticed it, so not too fussed...

**Comment by kolonuk** [comment]
Looks like this is fixed in v1.7.7...

**Comment by jcaillon** [comment]
Ah yes, perfect then :D
