### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by keahh** [jcaillon/3P#176]
### Description of the Issue

I have a temp-table called ttRes.
When I try to type ttRes.Field1 and I press the "." to add Field1, it replaces "ttRes" with START-RESIZE.

### Expected Behavior

The temp-table should be recognized and it fields should be part of the auto complete.

**Comment by jcaillon** [comment]
Hello,

Can you provide the incriminated code? Because this should work fine. The only possible explanation is a syntax that i did not take into account in the parser.

**Comment by keahh** [comment]
DEFINE temp-table ttResult no-undo
  
  field MandantID     like Artikel.MandantID
  field ArtikelNummer like Artikel.ArtikelNummer
  
  field cEanList as char
  field IEanNum as int 

  field iLiefNum as int
  field cIanList as char 
  .

**Comment by keahh** [comment]
I changed to ttResult cause of ttRest problems. Just rename back :)

**Comment by jcaillon** [comment]
Thanks for the answer, however I can't reproduce the bug. If i copy your code in an empty file and start typing `ttRest.` i get all the fields. 

Are you using the latest beta version (1.7.4)?

**Comment by keahh** [comment]
Please only 'ttRes' (without the 't'). And yes, 1.7.4, 64 Bit.

**Comment by keahh** [comment]
Similar is using a name like 'name1' will be substituted with 'WINDOW-MAXIMIZED1'.
So far, only way is to press ESC and then it will be not replaced.

**Comment by jcaillon** [comment]
Hi, there is a new release available. Can you check if the issue is still present?

**Comment by keahh** [comment]
I will try this week.

**Comment by jcaillon** [comment]
Hello, do you have any news? :)

**Comment by keahh** [comment]
Hello, I installed newest version and tried to reproduce, but now it shows the Temp-Table as first suggestion in list and that seems OK :)

There is still another issue (will not call it a bug).
When I add a variable where name fits in a keyword:
  DEFINE VARIABLE FirstA ...
When you type too fast, then it will replace 'FirstA' with 'FIRST-ASYNCH-REQUEST' when you press SPACE.
Reason is, it takes a second until the variable itself pops up in the suggestion list.

If you have problems to reproduce, I can try to attach a small video.
kind regards
keathh

**Comment by jcaillon** [comment]
Hello, thank you for the feedback, im glad it's fixed!

As for you second problem, I'm aware of the issue, the "problem" is that the auto completion is not deactivated after a DEFINE VARIABLE . It should not try to autocomplete after this 2 keywords because we know that it will be a new name.

I'm opening a new issue #193 for this.

Regards
