### ISSUE TITLE
Invisible char visible

### ISSUE THREAD

**Issue by keahh** [jcaillon/3P#177]
### Description of the Issue

The chars like tab or space are visible as dots or lines.

### Expected Behavior

Should be able to switch them off via generic settings.
Or via specific settings in "Main Menu".

**Comment by jcaillon** [comment]
Hello,

you can disable this feature in the menu, the option is called `Activate "show spaces" on progress files`. Once the options is toggled off you will need to switch to another document to refresh the editor.

![image](https://user-images.githubusercontent.com/11553075/31384800-de6016ee-adc0-11e7-9e5d-c71b087b9b3f.png)
