### ISSUE TITLE
File opening through Files Explorer

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#179]
### Steps to Reproduce the Issue

1.  Double click on a program in the files explorer

### Expected Behavior

The file opens in Notepad ++

### Actual Behavior

The file doesn't open In Notepad ++

### Debug Information

![image](https://user-images.githubusercontent.com/20086123/31883530-7a952008-b7ea-11e7-809f-b24c2802b41a.png)

**Comment by jcaillon** [comment]
Thanks for the feedback, this was indeed a pb related to notepad++x64 :)

**Comment by jcaillon** [comment]
If you want the corrected version right now you can download this build artifact, it's stable 👍 

https://ci.appveyor.com/project/jcaillon/3p/build/job/1cprnqw756uhklym/artifacts
