### ISSUE TITLE
automatic remove of function prototype

### ISSUE THREAD

**Issue by Damirko1** [jcaillon/3P#180]
### Steps to Reproduce the Issue

1.  put function definition in include file
2. put funct. proptotypes in main procedure file
3. 3p deletes prototype

### Expected Behavior

I need 3p to ask me if he should do delete

### Actual Behavior

3p deletes automaticaly

### Debug Information

3p 1.7

**Comment by jcaillon** [comment]
Hello, thank you for the feedback, this is already corrected in the latest beta version 1.7.5.
You can have it by checking "beta updates" in the Options > Update page

Best regards
