### ISSUE TITLE
open file in propath

### ISSUE THREAD

**Issue by Damirko1** [jcaillon/3P#181]
### Description of the Issue

3p opens file-name in code only if file exsist in source code directory

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

3p opens file-name in code  if file exsist  anywhere in propath 

### Actual Behavior

3p opens file-name in code only if file exsist in source code directory

### Debug Information

3p 1.7

**Comment by jcaillon** [comment]
Hello,

Thanks for the feedback, this will be corrected in the next beta version
