### ISSUE TITLE
No auto-completion with 3P v1.7.6 x64 vs Notepad x64

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#183]
### Description of the Issue
Press Ctrl + Space halfway through typing something.

### Steps to Reproduce the Issue

1.  Start typing something
2. Stop typing because you're lazy af
3. Press Ctrl + Space to let 3P finish the work

### Expected Behavior
A list with useful propositions based on what you've typed

### Actual Behavior
An empty list

### Debug Information

![image](https://user-images.githubusercontent.com/20086123/32093387-6273d388-bafc-11e7-9b95-de98acc79721.png)

**Comment by jcaillon** [comment]
Not a bug, you are positioned in a preprocessed line handled by the appbuilder which lists the objects that will be enabled at your program startup. But at this line, the fl_creation label is not defined yet (it is defined later in the code), so for 3P it doesn't actually exists yet...

You can disable this option but i would advice not to.

![image](https://user-images.githubusercontent.com/11553075/34733221-ee2217c8-f567-11e7-89f8-c5e88dd2e853.png)
