### ISSUE TITLE
Feature Request: Autocomplete should consider ALIASES

### ISSUE THREAD

**Issue by koelblinger** [jcaillon/3P#187]
Hi!

In our company we use multiple ALIASES for Databases. A million line of existing code is designed with this notation:

alias1.table.field

This causes issues with Autocomplete because 3P does not recognize the Table and so Autocomplete for Fields and Popup with Tableinfo get lost. 

Would it be possible, to make a Config Entry for a list of ALIASES in the Environment settings?

Maybe something like:

alias1,database1
alias2,database1
alias3,database2
alias4,database3
alias5,database3

this could have influence for Autocompletion or maybe the "Get DB Structure Button" ;)

Additionally it could be used to set ALIASES after Connecting databases, so there would be no need do to this with a pre-exection program.

CREATE ALIAS VALUE(ENTRY(1,cAliasLine)) FOR DATABASE VALUE(ENTRY(2,cAliasLine)).

Thanks,
Daniel

**Comment by jcaillon** [comment]
Hello Daniel,

This sounds like a good feature that would be useful for many users, I'll implement it.

If i understand correctly, you are currently using a 
![image](https://user-images.githubusercontent.com/11553075/32946958-f357e1ac-cb99-11e7-9b77-fa717a23238f.png) to create aliases dynamically? (just to make sure you have a workaround while waiting for this)

**Comment by koelblinger** [comment]
Thank You!

Yes, everything okay, i am using a pre-execution program.

Your solution is much more than ever expected!

You are doing a damned good job!

**Comment by RoHaX** [comment]
Hi!
I would like to have this feature as well and look forward to it being implemented.
Great Job!

**Comment by jcaillon** [comment]
Feature preview

![image](https://user-images.githubusercontent.com/11553075/36220581-68098822-11bb-11e8-9d91-d70bf478ca3e.png)

![image](https://user-images.githubusercontent.com/11553075/36220598-7fd592d4-11bb-11e8-8d4d-00aac3818da9.png)

**Comment by jcaillon** [comment]
Hi, the next beta release will ship this feature and should come **very soon**.

But you can't wait to try it and give me a feedback, you can download this build (x86 version) : 

https://ci.appveyor.com/api/buildjobs/kvbhfy7kg2x0xd2j/artifacts/Releases%2F3P.zip

**Comment by koelblinger** [comment]
Thanks Julien!

 

I tested and everything works perfect!

 

I think i am a heavy user -> my list of aliases:
kor,pcs_korn;doc,x_doku;pds,x_doku;sit,pcsschni;ptr,pcsschni;kos,pcsschni;kos2,pcsschni;bse,x_base;sec,x_base;pop,x_base;dru,x_base;glb,x_base;fff,x_base;mis,xmi_sys;ddb,xmi_sys;abr,xatabr;krzglb,xlkf_glb;lkfabr,xlkf_glb;lkfglb,xlkf_glb;patho,medi55;krzglb,xlkf_glb;lkfabr,xlkf_glb;lkfglb,xlkf_glb;patho,medi55;pvs,pcs_pvs;gfl,pcs_pvs;hst,pcs_pvs;hos,pcs_pvs;dwh,pcs_pvs;dps,pcs_pvs;dhs,pcs_pvs;mac,pcs_pvs;uds,pcs_pvs;dgf,pcs_pvs;bsx,pcs_pvs;ao,pcs_pvs;dbm,xathpt;dbn,xathpt;db1,xathpt;omo,xathpt;gmo,xathpt;bed,xathpt;lab,xatmed;kom,xatmed;anae,xatmed;anaedb,xatmed;ibst,xatmed;pfl,xatmed;sen,xatmed;med,xatmed;op,xatmed;tmp,xatmed;ris,xatmed;dsv,pcs_view;ref,pcs_ref;krz,lkfdata;krz,lkfdata;man,pcs_fws;his,pcs_fws;fib,pcs_fibu;anb,pcs_anbn;lag,pcslager;kor,pcs_korn

 

I also have dropped my workaround pre-execution programm to set the aliases for the database.

 

Code Completion, Syntax check and Compile works fine!

 

And the Message "Invalid ALIAS format, please correct it .... " when i made i mistype is also surprisingly pregnant!


thank you for beeing awesome,

Daniel

 

 

 

 

 

Gesendet: Mittwoch, 14. Februar 2018 um 19:21 Uhr
Von: "Julien Caillon" <notifications@github.com>
An: jcaillon/3P <3P@noreply.github.com>
Cc: koelblinger <daniel.koelblinger@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [jcaillon/3P] Feature Request: Autocomplete should consider ALIASES (#187)


Hi, the next beta release will ship this feature and should come very soon.

But you can't wait to try it and give me a feedback, you can download this build (x86 version) :

https://ci.appveyor.com/api/buildjobs/kvbhfy7kg2x0xd2j/artifacts/Releases%2F3P.zip

**Comment by jcaillon** [comment]
Eheh an impressive list of aliases indeed!
Thanks for the request and thanks for the feedback, im glad to help.
Since everything works fine ill create a new beta release tonight
