### ISSUE TITLE
Alt+F

### ISSUE THREAD

**Issue by Damirko1** [jcaillon/3P#189]
Hi,

### Description of the Issue

can't find shortcut "Alt+F" on schortchut list in options to delete it.

Now, when I hit Alt+F, insert new function show up, and i don't wont it!
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

File menu opened.

### Actual Behavior

Alt+F triggers dialog for  insert new function 
### Debug Information

notepad++ 7.5.4
3P 1.7.6 

Regards,
Damir

**Comment by jcaillon** [comment]
Hello,

See the screenshot below

![image](https://user-images.githubusercontent.com/11553075/34732248-fee7b48a-f564-11e7-8f8b-9136878a9d86.png)

Regards

**Comment by Damirko1** [comment]
Julien,

Thank you very much.
What can I say, I'm blind….
sorry

Best regards,
Damir




                Damir Pem
voditelj odjela IT-a


T
F
M
E
W
                +385 (1) 66 66 209
+385 (1) 66 66 299

Damir.Pem@sava-osiguranje.hr
www.sava-osiguranje.hr<https://www.sava-osiguranje.hr>
                Savska cesta 144a
HR-10000 Zagreb

<https://www.sava-osiguranje.hr/>[cid:logo_potpis_konacan_91c42baa-0421-4551-ad70-e27e27b9e337.jpg]<https://www.sava-osiguranje.hr/>

Ova poruka može sadržavati povjerljive informacije. Ako Vam ovaj e-mail nije namijenjen, molimo Vas da ga izbrišete zajedno sa svim njegovim privitcima i da nas o tome obavijestite. Ako Vam ovaj e-mail nije namijenjen, svaka upotreba, kopiranje, odavanje ili distribucija ovog e-maila ili dijela njegova sadržaja je zabranjena. Sva odgovornost za viruse je isključena do maksimalne razine dozvoljene zakonom.

**Comment by jcaillon** [comment]
No problem, don't worry ;)
