### ISSUE TITLE
Wrong procedure scope detection

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#19]
Hi !

It's me, again! I'm not your nightmare but I found something really strange. :)
Considering following ABL code, the procedure xx2, xx3 and xx4 and detected in the wrong scope: 
- Hovering on xx1 tells the procedure is scoped in "Definition block" --> OK :)
- Hovering on xx2 to xx4 tells the procedure is scoped in "Root" --> Wrong :(
- Same proble when displaying auto completion tooltin right after "RUN xx"

Thanks for fixing this.
Kind regards,
C.CLEAUD

-----
&ANALYZE-SUSPEND _VERSION-NUMBER AB_v10r12
&ANALYZE-RESUME
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _DEFINITIONS Procedure 
/*----------------------------------------------------------------------*/
/*          This .p file was created with the Progress AppBuilder.      */
/*----------------------------------------------------------------------*/

PROCEDURE xx1:
END.

PROCEDURE xx2:
END PROCEDURE.

PROCEDURE xx3:
END PROCEDURE.

PROCEDURE xx4:
END PROCEDURE.

RUN xx          /* Invoke auto-completion here */

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME

&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _MAIN-BLOCK Procedure 

/* ***************************  Main Block  *************************** */
RETURN "".

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME

**Comment by jcaillon** [comment]
This is an expected behavior, 

The app builder will never add a procedure or a function in the **DEFINITION BLOCK**, so this case will never happen.

Fyi :
The app builder uses `/* _UIB-CODE-BLOCK-END */` to know the end of a block. However, for performance considerations, i completely ignore the comments and don't try to match anything in them.
Thus, i consider that the definition block ends when another block (procedure, function, app builder block...) starts.

**Comment by ccleaud** [comment]
You're RIGHT, theorically!

But, one can create an include containing internal procedures and reference ths include file either in the definition block or in the main block.

I have seen such things. Especially when I was working for the team you are leaving :)

**Comment by jcaillon** [comment]
Take this example :

````
&ANALYZE-SUSPEND _VERSION-NUMBER AB_v10r12
&ANALYZE-RESUME 
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _DEFINITIONS Procedure

DEFINE VARIABLE gl_useWebService AS LOGICAL INITIAL FALSE NO-UNDO.
        
/* Défini la structure du dataset permettant la communication avec l'interface MAGIC */
{     sacmagicflux.i  }
{     inc/sacpsoalphatransdecla_def_tt.i  }  

DEFINE VARIABLE gi_exeCompta2 AS INTEGER INITIAL 0 NO-UNDO.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME
```

Both `gi_exeCompta2` and `gl_useWebService` are correctly affected to the definition block.

If, for instance, the include `sacmagicflux.i` contains a structured procedure with several internal procedures, they would all have the correct parent block as well, they would be flagged as external to the current file and found root block of the include file.

I consider this to be a consistent behavior so i won't change that :)

**Comment by ccleaud** [comment]
OK, understood. Pity.
You're right: this is bad practive but the ABL language allows developers to to such crapy things.
