### ISSUE TITLE
Duplicate an environment, then delete some databases

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#192]
### Description of the Issue
When copying an environment configuration, then deleting some database connexions, the database connexions are deleted in both environment configurations.

### Steps to Reproduce the Issue
1.  Select an environment (Set>Environment)
2. Click on "Copy"
3. Choose a new application suffix and description, then save
4. Delete some database connexions in the new environment.

### Expected Behavior
The database connexions are deleted in the new environment only.

### Actual Behavior
The database connexions are deleted in the new environment AND the original one chosen for the duplication.

### Debug Information
3P v.1.7.0

**Comment by jcaillon** [comment]
Hi, are you sure of the version number?

v1.7.0? this is not the latest stable version

**Comment by vvelletaz** [comment]
Yes ! (CRD environment)

Anyway, I have the same issue on v1.7.7 :)

2018-01-15 15:51 GMT+01:00 Julien Caillon <notifications@github.com>:
