### ISSUE TITLE
Índice fuera de los límites de la matriz.

### ISSUE THREAD

**Issue by nelsonleiva** [jcaillon/3P#194]
### Steps to Reproduce the Issue

1. Open notepad++
2. Write 25.
3. 

### Debug Information

1.7.7

============================================================
WHAT : Error in OnCharAdded : Índice fuera de los límites de la matriz.
WHEN : 17/01/2018 12:42:50
WHERE : System.String.get_Chars(), line 0
DETAILS : 
    System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
    en System.String.get_Chars(Int32 index)
    en _3PA.MainFeatures.AutoCompletionFeature.AutoCompletion.UpdateAutocompletion(Char c, Int32 insertPosition) en c:\projects\3p\3PA\MainFeatures\AutoCompletionFeature\AutoCompletion.cs:línea 309
    en _3PA.Plug.OnCharAdded(Char c, Int32 position) en c:\projects\3p\3PA\Plug.cs:línea 622

============================================================
WHAT : Error in OnCharAdded : Índice fuera de los límites de la matriz.
WHEN : 17/01/2018 12:44:41
WHERE : System.String.get_Chars(), line 0
DETAILS : 
    System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
    en System.String.get_Chars(Int32 index)
    en _3PA.MainFeatures.AutoCompletionFeature.AutoCompletion.UpdateAutocompletion(Char c, Int32 insertPosition) en c:\projects\3p\3PA\MainFeatures\AutoCompletionFeature\AutoCompletion.cs:línea 309
    en _3PA.Plug.OnCharAdded(Char c, Int32 position) en c:\projects\3p\3PA\Plug.cs:línea 622

![17-01-2018 12-53-35](https://user-images.githubusercontent.com/8809069/35052036-5dd63022-fb85-11e7-91d3-85f2f19af773.png)

**Comment by jcaillon** [comment]
Hi, 

I was able to reproduce, will fix asap. Thank you for the feedback

best regards
