### ISSUE TITLE
AutoPopulate DB Fields doesn't work for local buffers

### ISSUE THREAD

**Issue by gudzelayk** [jcaillon/3P#195]
DEFINE BUFFER ltable FOR table.

table.field - we don't have list of DB fields

**Comment by jcaillon** [comment]
Hello,

This works on my end, what is your 3P version?
Are you sure you extracted the database info through the environment page : 

![image](https://user-images.githubusercontent.com/11553075/35384375-61a02442-01c5-11e8-9719-a910c26b3435.png)

When you move the cursor on "table" does it show the tooltip for a table?

![image](https://user-images.githubusercontent.com/11553075/35384415-887d5134-01c5-11e8-847a-b85d1dcd7f3d.png)

**Comment by gudzelayk** [comment]
Thanks for quick response
It works for original table name
![default](https://user-images.githubusercontent.com/35800954/35384778-1a133948-01cf-11e8-8cd4-485f19c773e3.png)
But doesn't work in the case below(maybe the reason is with some include?) 
![default](https://user-images.githubusercontent.com/35800954/35384707-e3a0a5ee-01ce-11e8-863e-11cb31a2baf6.png)

**Comment by gudzelayk** [comment]
version 1.7.7

**Comment by gudzelayk** [comment]
Works without include 
![default](https://user-images.githubusercontent.com/35800954/35384936-8058175a-01cf-11e8-911e-4942684266bc.png)

**Comment by jcaillon** [comment]
Please send me a snippet of code that i can copy to new file to reproduce. I don't know what you have in the try.i, if i just copy/paste the code you are showing here it works fine.

**Comment by gudzelayk** [comment]
Leave it open with me for now as it works from time to time
I will try prepare new example

**Comment by gudzelayk** [comment]
works for me now
