### ISSUE TITLE
Check code validity

### ISSUE THREAD

**Issue by gudzelayk** [jcaillon/3P#196]
Do we have any possibility turn off this feature? v1.7.7

![default](https://user-images.githubusercontent.com/35800954/35385045-ccd705d2-01cf-11e8-8cdd-ee7793f664f7.png)

**Comment by jcaillon** [comment]
Yes there is : 

![image](https://user-images.githubusercontent.com/11553075/35388469-338e6f78-01d4-11e8-9949-46d8bac95a41.png)
