### ISSUE TITLE
Reload file loose styles and colors

### ISSUE THREAD

**Issue by gudzelayk** [jcaillon/3P#197]
I have some file 

![default](https://user-images.githubusercontent.com/35800954/35389058-dc606d2c-01de-11e8-85fe-b89d62567a68.png)

If I modify it from another place (e.g. revert change via git) and try to reload

![default](https://user-images.githubusercontent.com/35800954/35389098-0b5e9568-01df-11e8-943e-6305d68466a7.png)

I loose colors and styles

![default](https://user-images.githubusercontent.com/35800954/35389127-29f701f4-01df-11e8-9bfa-aceb7d532783.png)

To fix I need make some changes and save 
![default](https://user-images.githubusercontent.com/35800954/35389148-3c77e5aa-01df-11e8-8c51-7818f4bcf1db.png)

**Comment by jcaillon** [comment]
It works fine on my end with notepad++ v7.5.4 32bits and the 3P v1.7.7.

Do you have a custom user defined language for openedge?
![image](https://user-images.githubusercontent.com/11553075/35615157-9a7781ec-0671-11e8-815f-8bc62f663056.png)

**Comment by gudzelayk** [comment]
Yes I have
![default](https://user-images.githubusercontent.com/35800954/35615470-e2c32a10-067a-11e8-8c88-a60ff12e3826.png)

**Comment by jcaillon** [comment]
You should not have a custom UDL now because 3P has its own syntax colorization. Either you defined it or it was a left over from an old 3P installation that was not removed correctly.

**Comment by gudzelayk** [comment]
Yes, I did, but have the same :(

**Comment by jcaillon** [comment]
You might need to close/reopen the file and well as close/reopen n++.
Do you have the latest version of notepad++?

**Comment by gudzelayk** [comment]
Uploaded new version of N++. Looks like fixed now.

One more point which is related to this issue - If I press
![default](https://user-images.githubusercontent.com/35800954/35617391-bc15c25a-0680-11e8-8c82-25a28f5ac20f.png)

And reloaded all was good, so maybe 3P doesn't detect the file as progress?

Anyway you can close this issue as config

Thanks!

**Comment by jcaillon** [comment]
Alright perfect. Regarding your last comment, it makes sense that yuo had to flag the file as a progress file. Since it was originally associated with another language (the UDL language) 3P didn't try to read it as a progress file.
