### ISSUE TITLE
Keyword splitted over multi lines are not detected

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#20]
Hi,

I agree this case is really mad. But it should work.
The procedure yyy is not detected in the code explorer.

Thanks for fixing.
Regards, smiles and kisses
C.CLEAUD

-----
P~
R~
OCEDURE ~
yyy:
END.

**Comment by jcaillon** [comment]
This is **VERY** unlikely to happen!!!

However, it is corrected and will be available in the next release (v1.0.1)

**Comment by ccleaud** [comment]
You wanted me as a beta tester.
But, as you are discovering, I'm NOT just "someone" :)
Thanks
