### ISSUE TITLE
Cannon find userDefineLang.xml in %APPDATA%\Notepad++ path

### ISSUE THREAD

**Issue by grasor** [jcaillon/3P#200]
### Description of the Issue

When installing 3P in Notepad++ x64, the plug-in looks for a file userDefineLang.xml in the %APPDATA%\Notepad++ folder.  If the file is not present, the 3P plugin warns the user each time Notepad++ is launched.

The file userDefineLang.xml is NOT required by Notepad++ for default operation.

You can create a "NULL" userDefineLang.xml file containing:

<NotepadPlus>
  
</NotepadPlus>

and save it to the %APPDATA%\Notepad++ folder.  If you do that, the warning goes away.

### Steps to Reproduce the Issue

1. Perform a clean install of Notepad++ x64 (latest version)
2. Manually install the x64 plugin manager for Notepad++ x64
3. Using the x64 plugin manager, install 3P
4. Restart Notepad++
5. The warning dialog will appear if the userDefineLang.xml file is not found at %APPDATA%\Notepad++ path.

### Expected Behavior

For the 3P plugin to load when launching Notepad++ without generating a warning that it can't find the userDefineLang.xml file in the  %APPDATA%\Notepad++ path.

### Actual Behavior

The warning occurs...

### Debug Information
 1.7.7

**Comment by grasor** [comment]
The GitHub editor for posting comments did not allow the pasted XML contents of the userDefineLang.xml to be presented.  The contents of that file are (XML tags < and > replaced by { and }):

{NotepadPlus}
  
{/NotepadPlus}

**Comment by jcaillon** [comment]
Hi, you are right, ill correct it. Thank you for the feedback!

Regards
