### ISSUE TITLE
DB Structure Get - Critical error

### ISSUE THREAD

**Issue by johnnyhaff** [jcaillon/3P#211]
### Description of the Issue

After updating to the most recent version of Notepad++ (7.5.4) and 3P (1.7.7) I'm experiencing and issue when I "Get" the DB Structure from the Environment Setup screen.  I'm getting a Critical Error: 

Something went terribly wrong while using progress!
Below is the command line that was executed:
C:\Program Files\Progress\bin\prowin32.exe -b -p "C:\Users\rjh\AppData\Local\Temp\3P\exec_122407180_4wovixxk.hhp\run_122407243.p" -ininame "C:\Users\rjh\AppData\Local\Temp\3P\exec_122407180_4wovixxk.hhp\base.ini" -basekey "INI"

### Steps to Reproduce the Issue

1. Update Notepad++ to 7.5.4
2. Update 3P to 1.7.7
3. Click the "Get" button from the Environment Setup screen.

### Expected Behavior

I expected the DB Structure to be gotten from the database I have connected.
### Actual Behavior

Critical Error:
Something went terribly wrong while using progress!
Below is the command line that was executed:
C:\Program Files\Progress\bin\prowin32.exe -b -p "C:\Users\rjh\AppData\Local\Temp\3P\exec_122407180_4wovixxk.hhp\run_122407243.p" -ininame "C:\Users\rjh\AppData\Local\Temp\3P\exec_122407180_4wovixxk.hhp\base.ini" -basekey "INI"
### Debug Information

Notepad++ 7.5.4
3P 1.7.7

**Comment by jcaillon** [comment]
Hello Johny,

Which version of progress are you using?

Can you download this procedure and try to check its syntax please : 
https://raw.githubusercontent.com/jcaillon/3P/master/3PA/_Resource/Data/Progress/ProgressRun.p

If it compiles/check syntax with no errors then the next step will be to check your .ini file

regards,

**Comment by johnnyhaff** [comment]
Hi!
I get the same critical error when I check syntax through 3P.  I opened the file in the Progress Editor and checked syntax and it appears to not like the following line:
DEFINE VARIABLE llg_propath AS LONGCHAR NO-UNDO.

It's saying invalid datatype.

I am running version 9.1 Progress.

**Comment by jcaillon** [comment]
Alright, then look no further.
the LONGCHAR did not exist in 9.1 :/

I will provide a special build for you in the next hour so you can continue using the latest version.

**Comment by jcaillon** [comment]
Hi, 

Could you please download this version 👍 
https://ci.appveyor.com/api/buildjobs/0h305d8ynvv0rq6g/artifacts/Releases%2F3P.zip

And manually install it : 
- Stop notepad++
- Go to your notepad++ installation folder (usually %programfiles%\Notepad++), you should see a /plugins/ folder
- Unzip the content of the downloaded package into the aforementioned folder (/plugins/3P.dll should now exist)
- restart notepad++

To tell me if this works for you?

**Comment by johnnyhaff** [comment]
Excellent!  Works great, thank you!

**Comment by jcaillon** [comment]
Perfect, ill ship it officially with the next version
