### ISSUE TITLE
Prolint issue with Propath/Assemblies

### ISSUE THREAD

**Issue by echo1001** [jcaillon/3P#213]
### Description of the Issue
Propath in ini file and assemblies argument are affecting prolint.

### Debug Information
If I lint code from my source directory I get the following:

![image](https://user-images.githubusercontent.com/2708897/36602276-394b3c06-187d-11e8-9a1e-3b4facb6f7d1.png)

If I lint code from %APPDATA%\Roaming\Notepad++\plugins\Config\3P it will then throw the following error:

![image](https://user-images.githubusercontent.com/2708897/36602669-3557b132-187e-11e8-917e-cf4a7c8aab34.png)

Thanks!

**Comment by jcaillon** [comment]
Hi,

Both the PROPATH and the assemblies path for PROLINT are set in the `StartProlint.p` procedure which you can modify if you want. 
I think you modified this procedure and this is why you prolint is not working anymore.

Please try the following : 

- go to option > share/export config 
- search the prolint start up procedure line
- click on the delete button to reset this procedure

![image](https://user-images.githubusercontent.com/11553075/36609469-32c07626-18cd-11e8-83b1-43793960a561.png)

- try F12 (prolint) again

Tell me if it solves your problem

**Comment by echo1001** [comment]
Hello, 

This didn't solve my issue, but I figured out part of what it was and it was self-inflicted. I didn't install prolint correctly into the 3P/prolint folder. So sorry to bother you with this one.

I'm unfortunately still having issues with it not picking up the proparse.net assemblies. Placing them in my root assemblies folder does work around this issue. 

Thanks.

**Comment by jcaillon** [comment]
I imagine that you can't use the normal way to get prolint and let 3P download/install everything?

Here is what you should have in the folder `notepad++\plugins\Config\3P\prolint\proparse.net`  : 
```
assemblies.xml
ikvm.openjdk.core.dll
ikvm.runtime.dll
proparse.net.dll
```

Download those files from https://github.com/jcaillon/proparse/releases/download/v5.0.0.1/proparse.net.zip

regards

**Comment by jcaillon** [comment]
Please note that it would be better to let 3P handle it because it will be able to update prolint and proparse automatically. Also; if you are at the office and behind a corporate proxy, you can set up an http proxy to use in the options.
