### ISSUE TITLE
Deployment folder on Compile

### ISSUE THREAD

**Issue by gudzelayk** [jcaillon/3P#218]
.r and .xrf files after compilation are not moved to defined folder below

![default](https://user-images.githubusercontent.com/35800954/36895101-555cfabc-1e16-11e8-97d4-8a9aefc2fe20.png)

**Comment by jcaillon** [comment]
You have the toggle `Compile near source` ON.
As its name suggests, if you toggle it on, it will compile next to your source file (and not in the deployment folder).
Uncheck this and it will work as you expect.
