### ISSUE TITLE
Commenting throug 3P doesn't update the "file modified" flag

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#22]
Hi,

Let's play with this one:
1. open a Progress ABL source file
2. select a line, whaever you like
3. press CTRL+Q to comment
4. close Notepad++
5. no confirmation is asked to the user - however the file content has changed and file needs to be saved

Thanks for fixing his,
C.CLEAUD

**Comment by jcaillon** [comment]
I'm not sure to understand the problem,

What you are describing is true for any file in Notepad++, it never asks you to save a file when you **close Npp**, even if the file is modified (it just indicates that the file saved and the file in the editor are different with the small RED floppy disc on the file tab section).
However, if you try to **close the file** then it asks to save the file or discard modifications.

I'm closing this issue, re-open it if needed

**Comment by ccleaud** [comment]
My bad!
It was due to "remember current session for next launch" settings, int "Backup" preference.
You're right about closing it.
