### ISSUE TITLE
Get error on "Correct indentation" command

### ISSUE THREAD

**Issue by APenguini** [jcaillon/3P#221]
### Description of the Issue
Have several files that cause error when doing "Correct indentation" command. This seems to be related to the "editing" keyword.  I have the sample code:

   define variable vc1 as character.
   define variable vc2 as character.

   repeat:
      if vc1 = "" then do:
         update vc1 vc2 
         editing:
            if frame-field = "vc2" then message "in vc2".
         end.
      end.

      vc1 = "".
   end.

Here if you try Ctrl+I you will get the error. If you comment out the editing block, the error goes away.  I have some older code that I maintain that has editing blocks scattered throughout so need the "editing/end" pairs to match up.

Also, is there any way to determine or update the keywords that you have defined for OE ABL? If so I can fix and try on my side.

Thank you!

![image](https://user-images.githubusercontent.com/8633289/38211375-4078b336-3688-11e8-8ae9-12801458950b.png)

**Comment by jcaillon** [comment]
Hi,

Yep that's a mistake indeed. At the moment, the parser expects the `editing` keyword to be the first of the statement -> which is not how this keyword is used.

Thank you for the feedback, i'll fix it in the next version

**Comment by jcaillon** [comment]
Test program : 

```abl
define variable vc1 as character.
define variable vc2 as character.

repeat:
    if vc1 = "" then do:
        update vc1 vc2
        editing:
            READKEY.
            APPLY LASTKEY.
            if frame-field = "vc2" then 
                message "in vc2".
        end.
    end.
end.
```
