### ISSUE TITLE
3P Plugin crash notepad ++ when Compiling or Saving .w file 

### ISSUE THREAD

**Issue by haseogu** [jcaillon/3P#227]
### Description of the Issue

I updated 3p plugin to 1.8.1 from 1.7.x and this issue start happening.
The auto complete doesn't recognize database the field ( the field doesn't show up) when I open .w and I must restart notepad ++ so the plugin can work in .p.
I can't compile .w and save .w with the newest plugin (the notepad ++ crash immediately.
Code Explorer is stop working when I open .w file and will stop working until I restart the notepad++
Openedge version is 10.2A
.
### Steps to Reproduce the Issue

1. update plugin to 1.8.1
2. open .w in notepad++
3. compile or save .w or open the code explorer

### Expected Behavior

1. .w compiled
2. .w saved
3. code explorer show the structure of .w
### Actual Behavior

1. notepad++ crash
2. code explorer stop working (refresh icon )
3. database auto complete doesn't show the field of table.
### Debug Information

openedege v10.2A
notepad ++ v7.5.6(32bit)
3p 1.8.1

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : 3P.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![capture](https://user-images.githubusercontent.com/12505979/39470825-0ee8628c-4d6a-11e8-92a5-b0558925fc73.PNG)

**Comment by haseogu** [comment]
another screenshoot
![image](https://user-images.githubusercontent.com/12505979/39472299-9a812ad8-4d72-11e8-871f-9060f637f49e.png)

**Comment by jcaillon** [comment]
Hello,

The issue is pretty confusing, you seem to have several problems?

I understand that notepad++ crashes when you open a .w?
Or does it crashes when you try to compile a file?
Does it happen for all .w files? 
Can you send me a .w file that makes notepad++ crash?

(fyi, i'm not reproducing your issue at all, hence my questions)

As for the autocompletion problem, please make sure that you have the database structure extracted in your environment page : 
![image](https://user-images.githubusercontent.com/11553075/39537380-b63d6a08-4e39-11e8-994f-a723f5242080.png)
The extracted format has changed in 1.8.0

best regards

**Comment by haseogu** [comment]
Hi it's not happen to all .w file but mostly all the .w. the notepad ++ crash when I save or compile.w file. The database structure already extracted, but the field doesn't show up. I will post necessary file and lmage to explain it better later.

**Comment by haseogu** [comment]
Database doesn't show the field when I open .w file
![image](https://user-images.githubusercontent.com/12505979/39553973-7b64f25a-4e9a-11e8-9bd5-20d11fefa2ff.png)

Example of .w (zipped)
[wdeposit.zip](https://github.com/jcaillon/3P/files/1969232/wdeposit.zip)

**Comment by jcaillon** [comment]
Let's separate the problems.

1. For you database field

In your example, qq seems to be a input parameter FOR table. Is qq a table/temp-table known by 3P?
Is it a table from your database?

For instance, i have a table called _ActAILog and i define a input parameter for this table. If i hover the _ActAILog word with my mouse cursor, in the tooltip i should have : 
![image](https://user-images.githubusercontent.com/11553075/39575031-671f8cbc-4ed9-11e8-8e53-a0a701381813.png)

You see there are 2 (see 1/2 in the tooltip) definitions for this word, you can access the second with CTRL + Down arrow. The second definition is the table from the database, which is know by 3P because i extracted the databatase structure : 

![image](https://user-images.githubusercontent.com/11553075/39575198-f56c2444-4ed9-11e8-8676-2355ee90cc9e.png)

Other test, if you type "qq", it should appear twice in the autocompletion : 
![image](https://user-images.githubusercontent.com/11553075/39575258-29e86fe8-4eda-11e8-926c-d7681abe5ac3.png)

Otherwise, this means the table is unknown.


2. .w crashing notepad++

I unfortunately can't reproduce your problem. I can think of one more thing we can try : can you go in the options and set those two options like so  (in options -> code edition)

![image](https://user-images.githubusercontent.com/11553075/39575409-abe2c066-4eda-11e8-98b1-da527522108f.png)

Those two actions are done when saving/compiling a file. Maybe it is what causes a crash.


PS : do you check the .net framework requirement to run 3P? i.e. .net framework 4.6.2 must be installed

**Comment by haseogu** [comment]
do I need to install the specific version of .net or I can install the latest .net (4.7)?

**Comment by jcaillon** [comment]
4.6.2 or superior, the latest is fine

**Comment by haseogu** [comment]
I'm sorry I'm quiet busy right now, do you want some video to tell you the detailed problem ?
And I find that disconnect my pc from the remote database make 3p notepad work normally.

**Comment by jcaillon** [comment]
Hello, bug not reproduced and a lot of my questions didn't find answer. I don't have an idea on what causes this issue and there are too much modifications to consider between 1.7.7 -> 1.8.2.

Feel free to reopen this issue with replies to all the questions.

Best regards

**Comment by slegian** [comment]
I get the same crash issue on saving a file.

3p 1.8.3, 64x

I tried the 2 settings as advised above (disable auto update of functions ON and parser errors OFF), still crashes.

I can tell the crash will happen as the code explorer is blank when I open a file...

The only workaround to date is to wipe the plugin config (remove the "..\AppData\Roaming\Notepad++\plugins\Config\3P" folder).

**Comment by slegian** [comment]
The crash seems to start after I define the environment. 

I have an open edge file open, looks ok.

I go to the plugin settings, define an environment. Press the get data structure, that completes ok. I say view, i see the data. I then close the db structure info file, notepad++ switches to the open edge file, I get this error message:  "Vector<T> too long"

From then on the code explorer stops working and n++ will crash on save.

**Comment by slegian** [comment]
If I switch back to the default env, things start to work again...

**Comment by slegian** [comment]
Might be the propath. I tried setting up the environment step by step, the crash happens the moment I set the INI file, or if I set a propath.

**Comment by slegian** [comment]
Got it! ;)

It crashes if the value under "source directory" is also part of the propath.

Once I adjust the propath to remove the "source directory" from it we're back in business

**Comment by jcaillon** [comment]
Hello slegian,

Glad you find a way to make it work.

I still don't understand what happens however. 

- Do you have {include} files in your code? Maybe notepad++ crashes when the include file is actually found in the propath?
- Does the issue also appear if you put a `.` in the propath section? (you can put relative path to the source directory so this would designate the source directory as well)

best regards

**Comment by slegian** [comment]
Hi Julien,

Did a diff between the current, crashing 3P config folder and the original one. Found an error.log file which has this error multiple times:
WHAT : Error parsing C:\Users\slegian\AppData\Roaming\Notepad++\userDefineLang.xml : Index was outside the bounds of the array.
WHEN : 21/01/2019 3:00:33 PM
WHERE : v1.8.3, System.String.get_Chars(), line 0
DETAILS : 
    System.IndexOutOfRangeException: Index was outside the bounds of the array.
    at System.String.get_Chars(Int32 index)
    at _3PA.Lib.NanoXmlBase.GetValue(String str, Int32& i, Char endChar, Char endChar2, Boolean stopOnSpace)
    at _3PA.Lib.NanoXmlBase.ParseAttributes(String str, Int32& i, List`1 attributes, Char endChar, Char endChar2)
    at _3PA.Lib.NanoXmlNode..ctor(String str, Int32& i)
    at _3PA.Lib.NanoXmlDocument..ctor(String xmlString)
    at _3PA.NppCore.NppLangs..ctor()

Might give you a clue?

Cheers,
Simi

**Comment by slegian** [comment]
Hi Julien,

My userDefineLang.xml file is completely empty, 0kb file...

I commented out the includes and the code explorer finished parsing the file and shows the code breakdown. There is no more crash on save. So I think you are right about the includes causing this issue.

Cheers,
Simi

**Comment by jcaillon** [comment]
Cool! That's a good start, we know where to look. However, we (my teammates and I) are using a lot of programs with includes and it works just fine. So there must be something peculiar about the way your app uses includes (most likely a scenario that I missed when coding the parser).

Is it possible for you to reproduce the bug with the files stripped down to a minimum of lines (for confidentiality reasons, if needed) and to send them over? You can send them to my email if you want to make it less public.

**Comment by slegian** [comment]
Hi Julien,

I think I found it. The include file includes itself...

Attached a simple set of files that show the issue, at least on my machine.

test.p includes test.i which then includes test.i with a diff param.

When I open test.p in N++ the explorer hangs and then can't save...

Cheers,
Simi

[test.zip](https://github.com/jcaillon/3P/files/2781071/test.zip)

**Comment by jcaillon** [comment]
Great job sir! I was sure I handled this case, I guess not :/

I can partially reproduce the bug: it does crash the code explorer 

![image](https://user-images.githubusercontent.com/11553075/51524473-6991c300-1e2e-11e9-97ef-071529ebebe4.png)

...but it doesn't crash notepad++ on my end.

However, I am pretty confident that fixing this will also fix the crash.

I'll get back to you asap with a corrected version.

Thanks again for your help @slegian

**Comment by jcaillon** [comment]
@slegian
Hi Simi, this intermediate release should fix the issue: 
https://ci.appveyor.com/api/buildjobs/w491axf8j2aof6jy/artifacts/Releases%2F3P_x64.zip

**Comment by slegian** [comment]
Hi @jcaillon 

Hmm, could have sworn I added a comment earlier to say thanks for the fix and confirm it worked with my original test file...

Thing is it seems to hang on a different file, once I set up my env, so there must be some other scenario which triggers an infinite loop.

With this file it seems to hang only when I set the env. Without the env, the code explorer completes the parsing.

Is there any way we can disable the "include" files from the explorer?

Cheers,
Simi

**Comment by slegian** [comment]
We have a mix of paths with and without the src/ prefix, I wonder if that's what's causing the issue...

If I switch to the default env while the code explorer is "working", it completes and comes back with an include list like this:
![2019-02-07 12_29_14](https://user-images.githubusercontent.com/28940854/52385162-8ee02b80-2ad4-11e9-85da-10084ad546a5.png)

Notice the file shows up twice, once without the src/ prefix and then again with the src/ prefix and this "instance" repeats like mad, so chances this is what triggers the infinite loop.

The environment's "source directory" is that src folder, while the propath has both the src\ and the src\common folders.

**Comment by slegian** [comment]
[3p.227.zip](https://github.com/jcaillon/3P/files/2839038/3p.227.zip)

OK, managed to replicate with some custom files, attached.

There are 2 ways in which the infinite loop happens.

First, if I simply open the top "test.p" file. No environment set. The code explorer never finishes parsing this file.

The 2nd scenario is a bit more convoluted. You first need to set up an environment which has the "3p.227" folder as source directory and propath. Nothing else in the propath.

You then open the 3p.227\src\common\crash.p file. The code explorer never finishes for me.

If I drop the 3p.227 folder from propath, the code explorer finishes as it picks up only the test.i file and reports as missing include.

HTH

Cheers,
Simi

**Comment by jcaillon** [comment]
You are awesome! I will check that asap.

To give you a better understanding of why this fails:

Basically, at the moment, the parser is missing a function which evaluates the expression in a `&IF "{1}" = "DEFTEMP" &THEN`. What the parser *should* do, is ignore all the code in a false `&IF` block. With the correct behavior, if you code compiles, then the file is parse-able. But yeah, at the moment, the code in `&IF` is taken even if the expression false -> Hence the infinite recursions.

Also, i'm missing a feature that the progress compiler has: if the code is wrong and there is a bad case of recursion with include files, the compiler gives this error:

`Nested recursion limit of 255 exceeded in preprocessor expansion. (2936)`

I will implement this limit as well.

**Comment by jcaillon** [comment]
I have implemented the limit.

Here is what I have now for test.p:

![image](https://user-images.githubusercontent.com/11553075/52436962-f4a0d780-2b15-11e9-9eec-7a105012cba9.png)

And for crash.p:

![image](https://user-images.githubusercontent.com/11553075/52437081-45183500-2b16-11e9-89e0-2ca4ae29ef7e.png)

You can clearly see the crazy recursion going on and the max limit of 255 nested includes/preproc variables.


This is definitely not the perfect solution, but it should solve all crashes until I code the actual pre-processed expression evaluator :)

**Comment by jcaillon** [comment]
Version available here:

https://ci.appveyor.com/api/buildjobs/j7blhl7kaivru5hw/artifacts/Releases%2F3P_x64.zip

**Comment by slegian** [comment]
Thanks Julien. I downloaded the latest version and took for a spin. It does work with my test files, but unfortunately still has the hanging issue with the real production env/code... :(

I am not yet sure what the new scenario is, I'll see if I can find it and let you know.

As a workaround maybe have an option to bypass the include parsing, or parse an include file only once, not recursively, especially if the current parser cannot evaluate the pre-processor conditional logic. Maybe adding that is overkill anyway. So given my test.p file, it references test.i, parse that and when you hit test.i again, just ignore as it's already been parsed...

I'll be away next week, so will be quiet from my end :)

**Comment by jcaillon** [comment]
@slegian

Hi Simi,
I don't know if you are back yet; but I got a new version for you. It should fix the issue, hopefully!

https://ci.appveyor.com/api/buildjobs/t80nx340w56wcy05/artifacts/Releases%2F3P_x64.zip

**Comment by slegian** [comment]
Hi @jcaillon. I'm back. Got the latest version and so far it works. Thanks! I'll let you know should I run into any more troubles.

**Comment by jcaillon** [comment]
Perfect, thanks :)

Fyi, I will most likely publish a new release this week-end to ship this bug fix.
