### ISSUE TITLE
Code Explorer & File Explorer Refresh Problem

### ISSUE THREAD

**Issue by koelblinger** [jcaillon/3P#229]
When Notepad++ Window is moved, the container from Code Explorer & File Explorer do not refresh properly all the time.

If the Windows Performance settings flag "Show window contents while dragging" is turned off then the problem can be reproduced immediately.

Other Plugins using the same containers (eg. CS-Cript) dont have this problem.

My system: Windows 7 (64bit)

![grafik](https://user-images.githubusercontent.com/33750845/39803200-9cb669cc-5370-11e8-974f-b7f7b138250d.png)

**Comment by jcaillon** [comment]
Hi,

Thanks for the feedback. Im currently working on a complete rework of the UI, ill see what i can do about this while im at it.

best regards

**Comment by koelblinger** [comment]
Hi,

I made the fix for this.
Windows Moving and Resizing works now with a Hook for WM_PAINT

While i can't push to the project here is the zip:
[3p Window Move fix.zip](https://github.com/jcaillon/3P/files/2004507/3p.Window.Move.fix.zip)

regards,
Daniel

**Comment by koelblinger** [comment]
Hi Julien!

I made a pull request with a fix! ;)

regards,
Daniel

**Comment by koelblinger** [comment]
This was my first attempt, but it did not fire peoperly! 
WM_PAINT covers all useful cases (Mouse, Keyboard, Resolution Changes, ... ;)

**Comment by jcaillon** [comment]
Hello Daniel,

As stated here: https://github.com/jcaillon/3P/pull/230#issuecomment-437617187

The problem with using the normal way of docking windows in notepad++ panels is that it causes the program to freeze on tab or when moving the panels around. I'm not sure what is causing this behavior.

the current workaround seems acceptable to me at the moment (although it is definitely not perfect!). I'll be working on a rework of the yamui framework which might solve this problem but I personally will not put more energy into this issue (you are welcome to try if you wish, of course :)).

Best regards and sorry for the delay
