### ISSUE TITLE
Screen notifications displayed only on primary screen

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#23]
Hi,

Using 2 screens, and ofter using the primary (bigger) scren to look at videos while using the secondary (smaller) to code, I always see notification on the wrong screen over the video.

Can you display those notification on the screen displaying Notepad++?

Thanks for fixing!
Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
Fixed in v1.0.0

*There was also a problem with the auto-completion list, that would always show up on right/left side of the caret position (depending whether you primary screen was on the left or right of your secondary screen). This is fixed as well*
