### ISSUE TITLE
Code Explorer is not working after upgrade to 1.8.2

### ISSUE THREAD

**Issue by gudzelayk** [jcaillon/3P#232]
![default](https://user-images.githubusercontent.com/35800954/42457146-4f5c4da4-839f-11e8-87b0-d33112a62395.png)

**Comment by gudzelayk** [comment]
have a missed some new in setup?

**Comment by gudzelayk** [comment]
also tooltips with DB table is not working

**Comment by gudzelayk** [comment]
Working well if back to 1.7.7

**Comment by haseogu** [comment]
I already reported the same error in issue #227
