### ISSUE TITLE
"This is a beta version of the software" Typo

### ISSUE THREAD

**Issue by NeatCrown** [jcaillon/3P#237]
### Description of the Issue
There is a typo on the Main Menu's "This is a beta version of the software" section

### Steps to Reproduce the Issue
1. Open Main Menu
2. That's it

### Expected Behavior
Not a typo
"please let me know immediately (g͟i͟t͟h͟u͟b͟ is an efficient means)"

### Actual Behavior
A typo
"please let me know immediately (g͟i͟h͟u͟b͟ is an efficient means)"
![image](https://user-images.githubusercontent.com/27929028/48026016-c61bf680-e0f9-11e8-83dd-3d5f5232abfb.png)

Yes, I know a simpler report would have done for something as benign as this, but that isn't as fun though, is it?

**Comment by jcaillon** [comment]
No worries, issues are designed for this! Thank you for the feedback, I'll correct it :)
