### ISSUE TITLE
Regex problem in deployment rules

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/3P#238]
The following regex should work but it does not : `^.*(?<!srv)\.(p|cls)$ `.

**Comment by Asshiah** [comment]
I think this comes from the '<' symbol in the regex that the program understands as the beginning of a variable defined in the deployment rules file.
It expects an '>' symbol that never appears.

**Comment by jcaillon** [comment]
New rule: to escape a `<` or `>`, double it.

In our case, the regex in the deployment rules configuration becomes: `:^.*(?<<!srv)\.(p|cls)$`.

br
