### ISSUE TITLE
3p said "Notepad++ Crashed"

### ISSUE THREAD

**Issue by gurikbal** [jcaillon/3P#241]
3p said "Notepad++ Crashed" 

1. notepad++ can open in multi window when 2nd tab or any tab drag outside of notepad++ but 3p 3p said "Notepad++ Crashed"
![capture-20181117-110636](https://user-images.githubusercontent.com/36083297/48657679-c5208880-ea5a-11e8-8033-2ad16b06c824.png)

**Comment by jcaillon** [comment]
Thanks but this issue has already been reported. 

This is actually the first issue in the list: #239 . You will also see the aforementioned issue has been correctly created by following the issue template.
