### ISSUE TITLE
Custom folder for DataDigger: download/install if not existing in the external path

### ISSUE THREAD

**Issue by patrickTingen** [jcaillon/3P#242]
### Description of the Issue
When I enter a custom folder for DataDigger, 3P does not check there to see if it already exists

### Steps to Reproduce the Issue

1. Start 3P without a DD installed
2. Enter custom path for DD
3. Start DD from main menu (ctrl right click)
4. 3P gives error 'datadigger.p' not found, unable to exit

### Screenshots
![image](https://user-images.githubusercontent.com/6008861/48835009-7850f080-ed7f-11e8-8300-f5255135d6df.png)

I /think/ you check to see whether DD is installed in the default folder for DD whereas you should check the custom folder instead.

**Comment by jcaillon** [comment]
Hello Patrick, thanks for the issue. Does it work after a restart?

**Comment by Asshiah** [comment]
I had the exact same problem first.

I specified a folder like this 'C:\DataDigger' and I had this issue.

Then I tried 'C:\DataDigger\' with the trailing backslash and it just worked.

You should try this.

**Comment by patrickTingen** [comment]
No, a restart does not fix it. nor a slash at the end. I did another test and made sure there was no DD installed and no custom DD path. Then I pressed alt-d and chose 'explore and modify data'. N++ correctly asked me if I wanted to install DataDigger and it did correctly. DataDigger starts. 

Then I change the DD path to 'c:\work\datadigger'. Note that this is an empty folder. 
I press alt-d again and choose 'explore and modify data'. What I would expect here is that N++ would notify me that DD is not installed in 'c:\work\datadigger' and then offer me to download and install it there, just like it does with the default location. 

If I install it manually in 'c:\work\datadigger', all works like expected.

**Comment by jcaillon** [comment]
Oooh, ok. Then this is the expected behavior. This option is simply there indicate an external path where 3P can find an existing installation of datadigger (this is specified in the tooltip).

![image](https://user-images.githubusercontent.com/11553075/48968501-c0c31500-eff0-11e8-9f0e-b08a27544824.png)

But you are right, it could download/install if not found. I'll do that.

**Comment by patrickTingen** [comment]
Cool, thanks!
