### ISSUE TITLE
Help!! How to use this? css.xml cannot be used

### ISSUE THREAD

**Issue by abdulbadii** [jcaillon/3P#243]
How to use this? /plugins/API.css.xml autocompletion of NPP cannot be used
 How to use only NPP *.xml autocompletion not any from the currently edited text file ?

**Comment by jcaillon** [comment]
Sorry I don't understand the problem at all. Please reopen if you can correctly describe the issue.
You must use the template of bug report:

![image](https://user-images.githubusercontent.com/11553075/49575768-cb13d600-f943-11e8-928c-0dc56751e467.png)

When clicking on bug report:

![image](https://user-images.githubusercontent.com/11553075/49575788-d7982e80-f943-11e8-965e-a0e5901125b0.png)

You get a pre-filled text. You must not delete everything like you do. Instead you should try your best to correctly fill the form.
