### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by pedromagician** [jcaillon/3P#244]
The UI of the dropdown list is so tiny, I can hardly see it :( What are the options? Thanks.

Monitor:
24" - 1920x1200
27" - 2560x1440

**Comment by jcaillon** [comment]
Hello,

UI scaling is not *yet* supported by the ui framework used in 3P.

This will be far from perfect but you can try messing around with windows scaling:

![image](https://user-images.githubusercontent.com/11553075/49087873-57ddd600-f258-11e8-9a69-a1cec7ca26f3.png)

Try the different options, see if it suits your need.

I'd be happy to have a feedback on this

**Comment by pedromagician** [comment]
Settings does not impact :( Never mind!

Thanks for advice.

**Comment by jcaillon** [comment]
Sorry :/
you will have to patiently wait for a rework of the ui framework.
