### ISSUE TITLE
3P Autocomplete stopped working with new Notepad++ versions

### ISSUE THREAD

**Issue by pidgeon777** [jcaillon/3P#253]
### Description of the Issue

3P Autocomplete works by extracting words/functions from the `APIs` folder:

`C:\Notepad++\plugins\APIs`

In Notepad++ version 7.6.3, the XML files are moved here:

`C:\Notepad++\autoCompletion`

New 3P version should reflect this new Notepad++ behaviour.

**Comment by jcaillon** [comment]
Hi, thank you for reporting this bug.

It is already corrected and will be shipped with the next version (probably this weekend).

see #252 

You can try it here: https://ci.appveyor.com/api/buildjobs/kt29v2yt8k0bmifk/artifacts/Releases%2F3P.zip

**Comment by pidgeon777** [comment]
Extremely quick! Thank you.
