### ISSUE TITLE
Take into account the new possible location for user defined languages

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/3P#259]
Since notepad++ v7.6.4, UDL can be shipped in several .xml files, alongside the existing userDefineLang.xml.

See : https://notepad-plus-plus.org/community/topic/17072/new-enhancement-for-user-defined-language-system/19.

**Comment by pidgeon777** [comment]
I'm also really interested in this.

**Comment by jcaillon** [comment]
Linked to PR #270

**Comment by jcaillon** [comment]
Shipped with the next version
