### ISSUE TITLE
Show location of calls / runs

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#26]
Hi,

In the "Run statements" and "Dynamic function calls" in the "Code explorer" panel, can you add, right to the called entity, the location where the call is invoked please?

Thanks for considering this.

Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
Do you mean the block name? or the line? or the file? or everything? :)

Please note that my intention is to have tool-tips on both code exploer and file explorer list containing all the info of an item! Considering this, isn't this info too much for the list?

**Comment by ccleaud** [comment]
I think the entity name would be enough.
For example, knowing "myfunction" is called from "myprocedure" is a really interesting feature.
Thanks

**Comment by jcaillon** [comment]
It looks like this 

![image](https://cloud.githubusercontent.com/assets/11553075/11938249/dcaf4972-a819-11e5-8840-73e10162d8f2.png)

**Comment by ccleaud** [comment]
Yeah!

**Comment by jcaillon** [comment]
Done in v1.1.0
