### ISSUE TITLE
Alphabetize list items that show up in code explorer

### ISSUE THREAD

**Issue by smt62** [jcaillon/3P#260]

**Comment by jcaillon** [comment]
Do you mean like this:

![image](https://user-images.githubusercontent.com/11553075/58948223-eabc7780-8789-11e9-8a7f-c92b85c0a18f.png)

?

**Comment by smt62** [comment]
Hi,
Thank you!  I'm an idiot for not seeing that.
Love 3P.

Scott Turnamian
"Be who you are and say what you feel because those who mind don't matter and those who matter don't mind."

Dr. Seuss

 
 

    On Wednesday, June 5, 2019, 6:03:58 AM EDT, Julien Caillon <notifications@github.com> wrote:  
 
 
Closed #260.

**Comment by jcaillon** [comment]
No problem, I'm glad you like 3P :)

**Comment by smt62** [comment]
Hi Julien,
Been using 3P for awhile now.  Love it.  Everyone I show it to loves it.
If you need me to submit issues through Git, let me know and I'm happy use that route going forward.
Question.  Encountering a couple of odd things with one of my installations. 
   
   - Black boxes where 3P icons should be (3P works just fine other than DataDigger issue below) on NP++ toolbar - see attached
   - Have correct path for DataDigger but it will not load.  Used exact same path from AppBuilder tool pallet and DataDigger loads just fine.  

Scott Turnamian
"Be who you are and say what you feel because those who mind don't matter and those who matter don't mind."

Dr. Seuss

 
 

    On Thursday, June 6, 2019, 04:30:51 AM EDT, Julien Caillon <notifications@github.com> wrote:  
 
 
No problem, I'm glad you like 3P :)

**Comment by jcaillon** [comment]
Hi Scott, I will need more information to help you. Screenshots of your issue might help.
Your attachment did not get through github.

br

**Comment by smt62** [comment]
Hi Julien,  

Thanks for your quick reply. 

Hmmmm 

Thought I sent to both github and your personal email. 

What address should I use?

Thank you. 

Scott 



**Comment by jcaillon** [comment]
either use the github interface or write me an email directly at julien.caillon at gmail.com.
