### ISSUE TITLE
discoloring of unreleated lines during editing

### ISSUE THREAD

**Issue by sourcecodemaker** [jcaillon/3P#261]
Before I start complaining: 3P is an awesome addition for NPP and very much appreciated.
 
If I open a OpenEdge file the Highlighting works as expected. But as soon as I start typing the color changes in some of the characters in all following lines. Reloading the file with the saved changes fixes the display issue. Switching file tabs redraws the file correctly as well.

This is new to me and has happening since I got the new NPP version:
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : 3P.dll CodeAlignmentNpp.dll NppSnippets.dll PluginManager.dll _CustomizeToolbar.dll 

![Annotation 2019-06-04 103959](https://user-images.githubusercontent.com/33130941/58889067-5b925f80-86b6-11e9-98fe-73d0bd2aa9b4.png)

**Comment by sourcecodemaker** [comment]
Update:

- (re)istalled NPP keeping my setup - same issues
- (re)istalled 3P Plugin keeping my setup - same issues
- (re)istalled 3P Plugin deleting all settings - same issues
- installed **NPP version 7.6.6** keeping my setup - **no issues**

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : 3P.dll CodeAlignmentNpp.dll mimeTools.dll NppConverter.dll NppSnippets.dll PluginManager.dll _CustomizeToolbar.dll

**Comment by jcaillon** [comment]
Hi @sourcecodemaker, thanks for the feedback, much appreciated.

This is definitely a bug introduced by the upgrade of Scintilla from v3.56 to v4.14.
I'll try to fix that as soon as I have free time. Which might not be anytime soon :s

**Comment by jcaillon** [comment]
Closing this issue, you can follow #263
