### ISSUE TITLE
[ANNOUNCEMENT] Do not update to notepad++ v7.7 or above!

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/3P#263]
Version 7.7 of notepad++ is packing a new version scintilla (from v3.56 to v4.14). Some core functions of the component seem to have change and it causes various issues in 3P like :

- issue with the auto-completion no longer working #262 
- issue with syntax colorisation #261 

**While waiting for a new 3P release, please stick to the version 7.6.6 of notepad++.**

Thank you.

**Comment by pidgeon777** [comment]
Hello, any estimate date for the next 3P release?

Great job on the plugin, though!

**Comment by pidgeon777** [comment]
Thank you, Sir. Really, a big thank you.

Some of the 3P features were absolutely essential to me, now I can finally update Notepad++ to the latest 7.7+ version. Again, thank you for the early Christmas present! ;)

**Comment by jcaillon** [comment]
You are welcome, sorry for the delay and thank you for your appreciation :)
