### ISSUE TITLE
Syntax Highlighting Bug

### ISSUE THREAD

**Issue by whitmakr** [jcaillon/3P#269]
I'm not sure wherein this problem lies but after getting the most recent update, the syntax highlighting seems to bug out and change the colors.  Attached is a screenshot of me using the Sublime? syntax highlighting schema and you can see that some of the letters are cleared out like they're in a comment, some words have a mixture of colors, and some have the incorrect color altogether (DISABLE keyword should be pink, not green). The second screenshot shows that if you add code and then press return, the code gets highlighted in a white block with this color schema. In order for the code to have the correct highlighting again, I have to click to a different opened tab in Notepad++ and then click back for it to be normal again.
![syntaxhighlightingbug](https://user-images.githubusercontent.com/35874812/71182766-581e8a00-223c-11ea-923f-223a494c6837.png)
![image](https://user-images.githubusercontent.com/35874812/71182926-a03dac80-223c-11ea-8a7e-ec9437bd136e.png)

**Comment by jcaillon** [comment]
hello @whitmakr, can you give the version of notepad++ you are using?

Copy/paste the content of `Debug info`. for instance 👍 

```text
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1130
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

```

**Comment by whitmakr** [comment]
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : 3P.dll ComparePlugin.dll mimeTools.dll NppConverter.dll XMLTools.dll

**Comment by jcaillon** [comment]
Ok thank you. I think the problem is that : 

- the version 1.8.4 of 3P is incompatible with notepad++ v7.7 or **above**
- the version 1.8.5 of 3P is incompatible with notepad++ v7.7 or **below**

Can you try updating your notepad++ and tell me if it works better?

**Comment by whitmakr** [comment]
That seems to have done the trick, thank you!

**Comment by jcaillon** [comment]
Ok nice :)
I will update the minimal version of notepad++ required
