### ISSUE TITLE
Error in OnCharAddedWordEnd --> stack trace NOT logged in error.log file

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#27]
Hi again !

-----

An error has occured 
Error in OnCharAddedWordEnd 
The last action you started has triggered an error and has been cancelled.
1. If you didn't ask anything from 3P then you can probably ignore this message and go on with your work.
2. Otherwise, you might want to check out the error log below :
Link to the error log
Consider opening an issue on GitHub :
https://github.com/jcaillon/3P/issues
Level 0 support : restart Notepad++ and see if things are getting better!

-----

No information provided :(
Link to local log doesn't allow me to find what happens --> this exception seems NOT to be logged in the file.

**Comment by ccleaud** [comment]
Maybe some useful information for you:
On a multi-line ASSIGN (5 variables), I was deleting the last one (the one with the ending point).
Then, I added back the point at the end of the 4th line.
Again, thanks.
C.CLEAUD

**Comment by ccleaud** [comment]
This ticket needs adjustment: information has finally been pushed to github after 15 minutes.
It happens after a restart of Notepad++.
Please note the file "error.log" has not been updated, even 15 minutes later.

**Comment by jcaillon** [comment]
The error itself is already corrected in v1.1.0 (commented check).

The fact that the error.log was not correctly written... was it already open in an editor? It must have not had access to the file when it tried to write in it.

It will always be ok tho, because i have a phantom log file to send errors on github (error_.log)
