### ISSUE TITLE
Create a setting to allow / deny network accesses

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#28]
Hi,

Posting information on github when an error occured is not user friendly, especiually without asking the user if he really want this to happen.
Same remark with new version detection when the plugins starts up.

Can you create a setting to allow / deny 3P to go to the Internet please?
BTW, this will make possible to avoid the starting warning notification of 3P not able to reach github.
Thanks.

Reagrds,
C.CLEAUD

**Comment by jcaillon** [comment]
Done in v1.1.0

![image](https://cloud.githubusercontent.com/assets/11553075/11938134/e35a614a-a818-11e5-89b4-08561b763798.png)
