### ISSUE TITLE
3p looks in wrong dir for autocomete xml

### ISSUE THREAD

**Issue by Wrench36** [jcaillon/3P#286]
Notepad++ moved the language xmls from plugins/apis some time ago, and 3p still looks there.
I use 3p to load autocomplete suggestions from a customized lua.xml file for a flight simulation (DCS World) to add the custom DCS scripting commands.

**Comment by jcaillon** [comment]
Hello @Wrench36 , this has been fixed long ago in 3P, please check that you are up to date :)

https://github.com/jcaillon/3P/blob/master/3PA/NppCore/NppLang.cs#L36

**Comment by Wrench36** [comment]
I've checked that 3P is up to date, currently 1.8.7.
I've also checked that n++ us up to date, version 8.1.4.

The n++ default autocomplete is functioning as expected, but 3P isn't pulling any of the custom autocomplete I've added.
