### ISSUE TITLE
Auto Completion - Always does it even when I disabled the keys

### ISSUE THREAD

**Issue by DakotaMcCutch** [jcaillon/3P#290]
I don't know if this is a bug or just a not documented feature. But I have disabled the autocompletion keys for both entering and tab, but it still does the autocomplete when pressed, as well as the space bar does the auto-completion as well. The last one is more annoying than the other things.

Just cause I want to type press space, and it autocompletes to something I don't want it to.

**Comment by jcaillon** [comment]
Hi,

The correct option is the following:

![image](https://user-images.githubusercontent.com/11553075/161435833-5387b6a1-3e00-4a9a-9229-c6350915cfc0.png)

Found in autocompletion options page.

This should fix your issue :)

**Comment by DakotaMcCutch** [comment]
Thank you, I proably went up and down that list 20 times and never even seen that toggle
