### ISSUE TITLE
Getting Error on Deployment

### ISSUE THREAD

**Issue by DakotaMcCutch** [jcaillon/3P#292]
Every time I try to deploy an error comes up saying -rr is not a database parameter and was ignored. Over and over again. It only seems to happen when I actually hit start deployment cause it doesn't happen when I test it.

I am not an experienced Progress developer and can't seem to find the answers too this.

**Comment by jcaillon** [comment]
That's on you side; check the database connection string or prowin extra params for this (incorrect) option. If you have a -pf option check the associated pf file because the option can be in it.
