### ISSUE TITLE
3P is not compatible with notepad++ v8.4+

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/3P#294]
The syntax highlighting feature does not work after the [8.4 update](https://notepad-plus-plus.org/downloads/v8.4/) in which they introduced a [new version of scintilla](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10504). 

This also messes up the auto completion which is partially based on the caret highlight context to display things or not.

**Comment by TheMadTitan07** [comment]
@jcaillon are you working on a fix for this or is there a way around it besides going backwards in N++ versions? My organization keeps force updating N++ to 8.4 and causing 3P not to function properly.

**Comment by jcaillon** [comment]
@TheMadTitan07 I will check this week-end and see if i can fix it quickly.

After further the issue started with the [8.4 update](https://notepad-plus-plus.org/downloads/v8.4/) in which they introduced a [new version of scintilla](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10504).

**Comment by jcaillon** [comment]
@TheMadTitan07 a simple solution for you is to use the portable version of Notepad++; you do no need to install anything: unzip, add 3P with the plugin admin and you are good to go (you can have the version of notepad++ installed by your org and have this one locally for you only)

**Comment by HanzieV** [comment]
Works great ! Thanks !
