### ISSUE TITLE
Label forgotten from auto-completion

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#30]
Hi,

Considering imbricated loops, each one prefixed by a named label (making possible to break not only the local loop).
Those label names are not suggested by auto-completion.

Thanks for fixing.
Regards,
C.CLEAUD

-----
```
blk_loop1:
DO i = 1 TO 10 :
    blk_loop2 :
    DO j = i to 15 :
        /* xxx */
        LEAVE blk_loop1.  /* blk_loop1 is not in the auto-completion list */
    END.
END.
```

**Comment by jcaillon** [comment]
It is:

![image](https://cloud.githubusercontent.com/assets/11553075/11926784/e25edd6c-a7c7-11e5-8f45-9f3d2eeef114.png)

Send the whole program please, (make sure it compiles tho!) the snippet you provided works!

**Comment by jcaillon** [comment]
Okkk nevermind, it doesn't work on v1.1.0
