### ISSUE TITLE
Uninstall doesnt work. 

### ISSUE THREAD

**Issue by kylescollins** [jcaillon/3P#301]
### Description of the Issue
Uninstall isn't functional. 

### Steps to Reproduce the Issue
1. get stoned
2. install this plugin
3. regret installing this plugin
4. try to uninstall the plugin.
5. start at step one, originally 2 weeks ago. Guys, I don't smoke weed anymore. Why the fuck did this take over my np++ install?

### Expected Behavior
Uninstalled Plugin

### Actual Behavior
Close notepad, open notepad with admin prompt. Plugin still pluggin in.

**Comment by jcaillon** [comment]
I will ignore the rudeness of the comment and inform you that plugins are not responsible for their own uninstallation; you should open your issue on https://github.com/notepad-plus-plus/notepad-plus-plus.

For manual deletion, as documented by notepad++, you can also go to your plugin folder (`C:\Program Files\Notepad++\plugins` by default) and delete the 3P folder.
