### ISSUE TITLE
New type for external procedures

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#31]
Hi,

There are sections 'Events", "Procedures" and "Functions".
I think it would be nice to add a section "External procedure" for declaration of method / functions in a run-time library (.dll / .so).
Nice too to add the hosting library name.

Thanks,
C.CLEAUD

**Comment by jcaillon** [comment]
done!

![image](https://cloud.githubusercontent.com/assets/11553075/22943130/a9c23e92-f2ec-11e6-8891-da21bbc65b56.png)
