### ISSUE TITLE
Auto-completion does not show procedures and functions contained in local persistent run programs

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#33]
Hi,

Considering
```
RUN something.p PERSISTENT SET hSomething.
```
Auto-completion should propose internal procedures and functions contained in something.p.
I was surprised NOT finding such procedure, especially when my code already did calls to remote internal procedures.

Thanks taking this ticket into account.
Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
This is also because i sent you a bad version yesterday :)
It works now!
