### ISSUE TITLE
Error while duplicating code (CTRL+D)

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#35]
Hi,

Considering a file containing only this:
```
        RUN ScanInternalProcsAndFunctions (   INPUT ipiIdCarto,
                                              INPUT iphFSConfig,
                                              INPUT procarto.Appli.IdAppli,
                                              INPUT procarto.Prog.FichierParsing,
                                              INPUT procarto.Prog.FichierXref,
                                              OUTPUT liCountProcedure,
                                              OUTPUT liCountFunction).
```
Select all the file and press CTRL+D.
Two bad behaviors:
* it overrides the scintilla keyboard to duplicate text
* it pops an error window

**Comment by jcaillon** [comment]
Yeah my bad, the version i sent you yesterday contained a shortcut CTRL+D linking to a `Test()` method... 

`it overrides the scintilla keyboard to duplicate text`
This is totally intended.

You can change any plugin's shortcut from the npp menu (you will be able to do it from the application later on). Setting up shortcuts in Npp is a huge pain in the ass, i hook the keyboard events to be able to overwrite default Npp shortcuts. You can still access them, just change the shortcut for the 3P feature.

**CTRL+D** will never be used by 3P, this is only for a test!!
