### ISSUE TITLE
Wrong auto-completion popup location [HARD] [RANDOM]

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#37]
Hi,

I was editing a comment at th end of an ABL instruction.
The auto-completion window poped up and wrote a text in replacement of "END" of "END PROCEDURE".
Able to reproduce N times until I retsarted N++.

Sorry: I can't help you anymore.
No crash, no error notificaiton: jus wrong popup.

Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
It wrote `END PROCEDURE` instead of `END`? not sure to understand the bug description sorry!

**Comment by ccleaud** [comment]
No.
It replaced `END PROCEDURE.` with `PROCEDURE PROCEDURE.`.
Very strange.

**Comment by jcaillon** [comment]
This bug has been corrected with the commit [108](https://github.com/jcaillon/3P/commit/e1bd0b464d6a563accad3b345f5aeb37f8fc052e)

Please reopen it if you encounter the same bug in v1.1.0
