### ISSUE TITLE
Code explorer should be disabled when current file is not ABL

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#38]
Considering a normal text file open in Notepad++, the "Code explorer" panel shows the "Root" anchor.
When I click on it, the cursor moves to the top of the document.
Should'nt be the Code explorer disabled on NON ABL files?
Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
`When I click on it, the cursor moves to the top of the document.`
This is intended.

All non progress files will show a code explorer containing only the `root` item; I could also show an empty list, but i don't think it's disturbing.

I'll try, but i think i can't disabled (= hide the panel) each time the user switches to a non abl document without causing visual glitches in npp...

**Comment by jcaillon** [comment]
Done in the next version

![image](https://cloud.githubusercontent.com/assets/11553075/12366602/7560ca44-bbdc-11e5-8e53-05cbdafbdb02.png)
