### ISSUE TITLE
3P option window won't display on NON ABL files

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#39]
Hi,

On a .txt files, I wanted to check my 3P options.
The window never showed.
I had to switch on a ABL file to display it.

Can you fix this, please?
Thanks

**Comment by jcaillon** [comment]
Yes, i'm not allowing the execution of 3P's features outside progress files;

However, the main application should be available at any time, i'll change this behavior.

Fixed in v1.1.0
