### ISSUE TITLE
List temp-tables in code explorer

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#40]
Hi,

Can you add a section for temp-tables defines in the program in the "Code explorer" panel?
Thanks!

Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
I'm not sure that it is a useful information to have in the code explorer *which is already heavily loaded with info*, plus you already have the list of temp tables with CTRL+SPACE (auto completion list) and filtering by temp tables (the yellow folder).

What' do you think?

**Comment by ccleaud** [comment]
I think Code explorer should show an outlook of the file:
* procedure declarations
* function declarations
* temp-table declarations as well

**Comment by jcaillon** [comment]
Ok, i'll add it to the list :)

**Comment by ccleaud** [comment]
Thanks :+1:

**Comment by jcaillon** [comment]
done!

![image](https://cloud.githubusercontent.com/assets/11553075/22944453/09451840-f2f1-11e6-918a-53430201af9c.png)

I will add the tooltip on the code explorer :soon: 
so we can easily see the fields of each tt
