### ISSUE TITLE
Auto-completion opacity not taken into account because of exception when saving changes

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#47]
Hi,

Statring N++ with opacity settings:

* 0.85 for unfocused
* 0.95 for focused

I decided to change to 1 the focused opacity...
I went to option, types "1" then clicked the red floppy disk.

* Thread error + log (always reproductible, causing changes to be ignored)
* Opacity is not full

I went back to the option panel and changed and daved again the value. No exception this time but the opacity is still NOT 100%

Thanks for fixing.

**Comment by jcaillon** [comment]
Fixed in the next release, happened when either the code explorer or the file explorer was hidden when clicking the save button.
