### ISSUE TITLE
Check syntax causes graphic glitches

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#48]
Check syntax causes graphic glitches.
But the text document seems not to be altered:
![2015-12-28 23_29_33-item-87166 dhcp lyo2 fr sopra - remote desktop connection](https://cloud.githubusercontent.com/assets/7109720/12026534/ec8a1ce0-adba-11e5-866c-cfaa18086a02.png)
.
1. Open a Progress source code
2. Menu Plugin > 3P > Check syntax
3. Here you are

Current version is 1.1.1.
Thanks for fixing.

**Comment by jcaillon** [comment]
I'm on it;

This is NOT easily reproducible tho, most of the check syntax go smoothly. But ye i already encountered this myself. I'll keep you posted when it's corrected

**Comment by jcaillon** [comment]
Fixed in the next version!
