### ISSUE TITLE
Create dinstinct types for runs/calls

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#5]
Hi,

Can you create more sections in the Code explorer :
- static function calls
- dynamic function calls
- internal procedure runs
- external programs runs
- dynamic calls
- internal callback reference
  Thanks for considering this ticket.

Kind regards,
C. CLEAUD

**Comment by jcaillon** [comment]
done :)

![image](https://cloud.githubusercontent.com/assets/11553075/22942614/85547ffe-f2ea-11e6-8180-1098c4098686.png)
