### ISSUE TITLE
Assume default PROPATH for include files in current source directory

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#50]
Hi,

Can you make 3P assume the default PROPATH is ".", where "." means the current source directory, even if there is no customized PROPATH?

This will allow 3P to parse include files contained in the same directory as the source.
Obviously, if the include pre-processor is directory-relative (like `{mydfir/myinclude.i}` or `{../includes/something.i}`, 3P should take this relative path in to account.

Thanks a lot for this!

Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
Done in the next version, the relative path will also work correctly
