### ISSUE TITLE
After 12 hours without stopping N++, 3P fails to show auto-completion list

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#53]
Sorry, no idea of what happened.
No exception occurred.

**Comment by jcaillon** [comment]
Did you try to switch documents? or press refresh? did you try to force it with CTRL+SPACE? were the other features working?
I don't see what i can do here!

**Comment by ccleaud** [comment]
I don't see what you can do here too.
But you now know this kind of problem occurred.
I suggest tagging this issue as "Help wanted".

**Comment by jcaillon** [comment]
This issue looks irrelevant in the newest version of 3P. To reopen if it ever happen again
