### ISSUE TITLE
Auto-completion occurs even if it shouldn't

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#55]
Hi,

In this **existing**  comment: `   /* Append information in TEMP-TABLE */    `
I want to replace `in` with `to file list`

Auto-completion pops up and insert keywords in uppercase.
Please note the 'Show list in comments and string' is set to NO.

Can you fix this, please?
Thanks

**Comment by ccleaud** [comment]
It's working after some minutes.
I changed a settings before noticing the bug.
Maybe it's not clear for the user when its settings are taken into account.
--> Show a notification popup when settings change is detected?

**Comment by jcaillon** [comment]
Fixed in the next version
