### ISSUE TITLE
Cut entity name in tooltip

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#56]
I like to use meaning names to my variables / temp-tables and so on.
I nammed my TEMP-TABLE `tt_batch_compile_settings_full`.
As you can see in the screen capture, the tooltip cuts the name.
Can you fix thix, please?

-----

![2015-12-30_113139](https://cloud.githubusercontent.com/assets/7109720/12049581/266f47da-aee9-11e5-80cb-97cc1066d576.png)

**Comment by jcaillon** [comment]
Corrected in the next version
