### ISSUE TITLE
Troubles with auto-completion popup : auto insertion of wrong keyword in wrong place at wrong moment (user didn't validate insertion)

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#57]
Don't know how to reproduce.
There was no exception notification before this problem occurred.
This problem didn't show any exception notification.
Bug happened when typing ':'.

To view the problem, just rename the .zip file to .mp4 and play it.

Thanks for fixing.

-----

[2015-12-30_113117.mp4.zip](https://github.com/jcaillon/3P/files/74765/2015-12-30_113117.mp4.zip)

**Comment by jcaillon** [comment]
The BYTE to CHAR /  CHAR to BYTE class has been fully revamped in commit : [106](https://github.com/jcaillon/3P/commit/70b1d0d82b04d189a51bba4a0779dfc0a45c9c62).

This problem will not occur anymore

Fixed in the next version
