### ISSUE TITLE
Text tokens wrongly considered as keyword

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#58]
If a string contains a word that is a Progress ABL keyword, 3P believe this is a keyword.
@see https://github.com/jcaillon/3P/issues/57 for details, at the end of the video
Thanks for fixing

**Comment by jcaillon** [comment]
I'm not sure that I'm not "fixing" a useful feature here; but ok :
*in strings, only the words of type **function** trigger the tooltip*

In next version
