### ISSUE TITLE
Handle publish & subscribe

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#6]
Hi,

It seems PUBLISH and SUBSCRIBE keywords are not detected in the code explorer
Can you handle those keywords please?

Kind regards,
C. CLEAUD

**Comment by jcaillon** [comment]
The parser now recognizes the keywords `SUBSCRIBE` `UNSUBSCRIBE` and `PUBLISH`, the statements are displayed on the code explorer (fixes #6)
