### ISSUE TITLE
Missing keywords: YES, NO, TRUE, FALSE

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#60]
Following keywords are not proposed in the auto-completion list:
* YES
* NO
* TRUE
* FALSE

Can you add them, please?

**Comment by ccleaud** [comment]
After some minutes, the keyword is now shown in the list.

**Comment by jcaillon** [comment]
Corrected by this commit : 
[https://github.com/jcaillon/3P/commit/70b1d0d82b04d189a51bba4a0779dfc0a45c9c62](https://github.com/jcaillon/3P/commit/70b1d0d82b04d189a51bba4a0779dfc0a45c9c62)
