### ISSUE TITLE
Add a "begins" button under auto-completion popup

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#63]
Auto-completion shows all words containing previously typed letter, no matter if there are other letters between them.
Although this is a cool feature, it's sometimes annoying (currently, this is).

Can you add a button to filter and sho only tokens strictly begining with letters types by the user?

Thanks a lot.
Reagrds.

**Comment by jcaillon** [comment]
I created a new filter algo to improve the suggestions in both file explorer and auto-completion list.

Released in the next version
