### ISSUE TITLE
EditBox horizontal scrolling is not smooth

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#65]
In the edition panel, when you have a long text to write in a edit-box, the scrolling is not smooth.
For instance: the "Modification tag : opener"
Moreover,
* the <END> key doesn't work (it doesn't move the cursor to the end of the text but only to the end of the visible text
* same for the <HOME> key
Can you fix, please?
Thanks a lot.

**Comment by jcaillon** [comment]
I think you are missing words :p
Well, this is the default behavior of a text box with multi-lines and i HAVE to set it to multi-lines if i want to be able to draw the border and make it all pretty...
I'll try to find another way, but i'm afraid this issue is on the bottom of the list!

**Comment by jcaillon** [comment]
I'm closing this issue as the ratio (importance)/(time to spend to correct it) is pretty damn low :)

**Comment by jcaillon** [comment]
Well... The devil is in the details... Bug corrected in the next release v1.5.4
