### ISSUE TITLE
Support single-line comments and hex literals

### ISSUE THREAD

**Issue by MGilarde** [jcaillon/3P#67]
OpenEdge supports single-line comments starting in 11.6. Single-line comments begin with "//" (two forward slashes). The slashes must be preceded by whitespace (space, tab, or newline).

Valid comments:

// start of line
BELL. // end of line
BELL. //end of line

Invalid comment:
BELL.// need space or tab before //

OpenEdge also supports hex literals of the form 0xNNNN where NNNN represents any number of hex digits, either uppercase or lowercase. This has been supported since 10.0A.

**Comment by jcaillon** [comment]
Hello,

Thank you for using 3P and thank you for this feedback!
I will make sure to include this evolution in the next release (should be available within 1 week).

**Comment by MGilarde** [comment]
Also, there are new keywords in every release of OpenEdge. I noticed that some keywords like ENUM, DYNAMIC-ENUM, XOR, and others which were added in 11.6 are missing. Do you need a complete keyword list? I can generate one for you.

**Comment by jcaillon** [comment]
Yeah this could definitely help! As you noticed already, I'm using an older version of Progress for my devs (11.10).

The keyword list used by 3P is here : 
[https://github.com/jcaillon/3P/blob/master/3PA/Data/KeywordsList](https://github.com/jcaillon/3P/blob/master/3PA/Data/KeywordsList)

You can either fork the project and submit a merge on this file or send me an updated list and I'll do it.

Thanks!

**Comment by MGilarde** [comment]
Here's a list of keywords which were added since 11.0 which aren't in your list.

BLOCK-LEVEL (Abbreviation BLOCK-LEV)
BUFFER-PARTITION-ID
CAN-DO-DOMAIN-SUPPORT
DYNAMIC-ENUM (Reserved)
ENTITY-EXPANSION-LIMIT
ENUM
FLAGS
GET-CLASS
IS-PARTITIONED
LABELS-HAVE-COLONS
PROCESS-ARCHITECTURE
ROLE
SERIALIZABLE
SET-ROLE
SINGLE-RUN (Reserved)
SKIP-GROUP-DUPLICATES (Reserved)
SOAP-FAULT-MISUNDERSTOOD-HEADER
SOAP-FAULT-NODE
SOAP-FAULT-ROLE
SOAP-FAULT-SUBCODE
SOAP-VERSION
STRICT-ENTITY-RESOLUTION
TENANT
TENANT-WHERE (Reserved)
THREAD-SAFE
UNDO-THROW-SCOPE
XML-ENTITY-EXPANSION-LIMIT
XML-STRICT-ENTITY-RESOLUTION
XOR (Reserved)

**Comment by jcaillon** [comment]
Hi,

Thank you very much for this list, I've added all the keywords except `TENANT` and `TENANT-WHERE` which i can't find in the Reference help of progress 11.6? I need to know if they are an Attribute/Function/Method/Statement/Option.

Fyi, I've done the modifications to include the single line comments (see screenshot below) + handling hexa numbers.

![image](https://cloud.githubusercontent.com/assets/11553075/13824325/d273f4a8-ebad-11e5-9078-264b933fe068.png)

**Comment by MGilarde** [comment]
TENANT is an option on the CREATE statement: CREATE record [ FOR TENANT tenant-expression ]

TENANT-WHERE is an option on the Record Phrase, like WHERE.

**Comment by jcaillon** [comment]
Nice ;)
I've added them as well

**Comment by jcaillon** [comment]
Hello,

A new release is available and contains the modifications we talked about :)

Since it is a *beta* version, you need to check the "Get beta version option" in order to be able to automatically update from your *stable* version (1.4.0). See below:

![image](https://cloud.githubusercontent.com/assets/11553075/14001906/c8b9f17e-f148-11e5-9b5c-083c60b4ebab.png)

Toggle the option to true and click `Check for updates`!
