### ISSUE TITLE
Custom shortcut mapping

### ISSUE THREAD

**Issue by TestUser013** [jcaillon/3P#68]
Hi.
I have one more wish :)
There are no possibility to change shortcut defined by this plugin. I think, will be useful to add shortcut this plugin in to Settings -> Shortcut mapper window.

Thank you :)

**Comment by jcaillon** [comment]
Hey, 

You are totally right, this has been on my todo list for too long, I have to do this for the next release :)

However, I won't let notepad++ handle this, it will be changeable through the `OPTIONS` > `SHORCUTS` page.

I'll keep you posted

**Comment by jcaillon** [comment]
Done in v1.4.2,

sorry for the delay :)

![image](https://cloud.githubusercontent.com/assets/11553075/14614055/a8bf22e8-059f-11e6-9479-702437981f14.png)
