### ISSUE TITLE
Minimum version of Windows required?

### ISSUE THREAD

**Issue by kger** [jcaillon/3P#70]
I tried installing Notepad++ and 3P on a remote machine running Windows Server 2003 R2 and Notepad++ started up with the error that 3P was not compatible "with this version of Notepad++".  Since the same combination works just fine on my Windows 7 laptop, I suspect the old version of Windows on the remote machine is the root problem.

is there a minimum required version of Windows for 3P?  Or, is there another required Microsoft DLL that I can try installing on the older machine?

**Comment by jcaillon** [comment]
Hello,

It might have to do with your .net version, 4.0 si required at minima :
[https://www.microsoft.com/en-us/download/details.aspx?id=17851](https://www.microsoft.com/en-us/download/details.aspx?id=17851) 

If it still doesn't work, can you send a screenshot of the error?

**Comment by kger** [comment]
OK, thanks.  I figured it had something to do with that.  I will try it out and report back.

**Comment by jcaillon** [comment]
Hello, 

Did you manage to get it working?
