### ISSUE TITLE
File explorer tooltips

### ISSUE THREAD

**Issue by vvelletaz** [jcaillon/3P#73]
![3prequest](https://cloud.githubusercontent.com/assets/20086123/16331618/c865c756-39f1-11e6-9ac1-9fd7d7ded7b3.png)

When two different files with the same name are openend from different directories, it would be usefull if a tooltip shows the file's directory.

**Comment by jcaillon** [comment]
Will do the tooltip but for now this is partially answered since the file explorer is now displayed as a tree view

![image](https://cloud.githubusercontent.com/assets/11553075/22990329/164d03ae-f3b9-11e6-815f-d1d97cfa972b.png)
