### ISSUE TITLE
Event name mis-detected

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#8]
Hi,

Following code is detected in EVENT section but the event name is U instead of CLOSE.
Can you fix this, please?

King regards,
C.CLEAUD

/* ***************************  Main Block  *************************** */
ON "CLOSE":U OF THIS-PROCEDURE DO:
    UNSUBSCRIBE TO "LogError".
    UNSUBSCRIBE TO "Sleep".
    DELETE PROCEDURE THIS-PROCEDURE.
END.

**Comment by jcaillon** [comment]
**Ok**

Corrected in the next release (v1.0.1)
