### ISSUE TITLE
Includes file and preprocessor directive

### ISSUE THREAD

**Issue by TestUser013** [jcaillon/3P#81]
Hi,
I found some issue in code explorer.
If include file name has preprocessor directive this include file do not shown in code explorer.

For example:
&GLOBAL-DEFINE US_SO 'lang_us/so/'
{{&US_SO}filename.i}

**Comment by jcaillon** [comment]
Hi,

Indeed, I didn't cover this case when building the parser, I'll add it in the next release.

Ty

**Comment by jcaillon** [comment]
Next version will handle a lot more cases regarding preprocessed variables; below is an very dirty (purposefully) example of what the parser can handle :

```
&GLOBAL-DEFINE US_SO lang_us/
{  {&US_SO}hello.f    
    &1=one   /* a comment*/
    &2="deux"}
{ext define var lctess as CHARACTER "this is a test"}
&GLOBAL-DEFINE hello        hello      
&GLO~
BAL-DEFINE he        he     
&GLOBAL-DEFINE message ~MESSAGE     
&GLOBAL-DEFINE test {&message    } "this is a test {&hello}" VIEW-AS ~
     ALERT-BOX.

~DEF~
INE VARIABLE lc_{&{&he}llo

} AS CHARACTER NO-UNDO ~IN~ITIAL "YO!".

~DEF~
INE~ VARIABLE lc_ho AS CHARACTER NO-UNDO ~IN~ITIAL "YO!".

{&test}
MESSAGE lctess.
MESSAGE lc_hello.

RUN {&US_SO}test.p.
```
