### ISSUE TITLE
Background color in simple file

### ISSUE THREAD

**Issue by TestUser013** [jcaillon/3P#83]
I use standard dark color style (Deep Black). 
First I opened *.p file. Next I have created new file and active line (with cursor) in this file has white background color. But this line should be dark gray. After restart NP++ background color is dark gray as usual.

**Comment by jcaillon** [comment]
Oh indeed, I restore the colors from the stylers.xml which is the default theme of notepad++.
Will be fixed in the next release.

Note to self :
Use `<GUIConfig name="stylerTheme" path="C:\Work\3P_notepad++\themes\Deep Black.xml" />`
in config.xml to know which xml to read

**Comment by jcaillon** [comment]
Done  in v1.7.1. Since I read config.xml, if you change your theme, you will have to restart npp for 3P to correctly restore your theme's colors in non progress files
