### ISSUE TITLE
-Mm parameter

### ISSUE THREAD

**Issue by rlfritz** [jcaillon/3P#84]
Hi.

I do like to connect a database with a .pf file parameters. But a error occurs when database is connecting. 
(1150): Servidor tem -Mm param 2048 e client tem 1024. Eles devem estar iguais. (1150)   
(I´m in Brazil. The error is in Portuguese.)

The .pf file is configured to -Mm 2048 but the 3P not read this configuration and try connect with -Mm 1024.
I tried to configure the connection in "Extra connection" section, but the problem persist.

Thanks.
Robert

**Comment by jcaillon** [comment]
Hi,

Sorry for the late answer, I was on holidays =)
3P uses the .pf file directly (i.e. `-pf file.pf`) so this error looks strange to me. Please try the following solution : 
In set environment, try this option 
![image](https://cloud.githubusercontent.com/assets/11553075/17823915/363752d8-665f-11e6-9f60-093a7bd79931.png)

Tell me if it worked for you!

Bye

**Comment by rlfritz** [comment]
Hi

I changed the -Mm parameter with your indication (Prowin extra params).
Conection with sucess!
Thanks

**Comment by jcaillon** [comment]
Perfect! You're welcome, glad it workded :)
