### ISSUE TITLE
Color scheme is applied to files outside of configured Progress 4GL extension list

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#87]
It seems the color scheme depends on the beginning of file extension.

For instance, if you specify `.p,.i,.w,.t,.d,.lst,.df,.cls` as `Progress 4GL files extension list` (in the Options > General tab) and you open a C file (myfile.c), you'll see the selected color scheme wrongly applied to that file.

**Comment by jcaillon** [comment]
related to issue #80

**Comment by jcaillon** [comment]
thx, done
