### ISSUE TITLE
Auto-completion failure when caret is in overwrite mode

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#89]
Considering this piece of code:
`DEFINE VARIABLE lcCommandLineCompil         AS CHARACTER    NO-UNDO.`
To be replaced to this one:
`DEFINE VARIABLE lcCommandLine               AS CHARACTER    NO-UNDO.`

Process following steps:
1. switch to overwrite mode
2. move caret under the C of `...LineCompil`
3. press SPACE (in order to erase `Compil`
4. auto-completion pops up then disappears and the text is now `DEFINE VARIABLE lcCommandLineCompil ompil         AS CHARACTER    NO-UNDO.`

Can you please fix that?

Thanks

**Comment by jcaillon** [comment]
Thx, this is fixed indirectly by #136
