### ISSUE TITLE
Missing "Connected Databases" section

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#9]
Hi,

Sometins a program references database connections.
The section is recognizable using "/* Connected Databases " pattern.
Can you add it, please?

Thanks a lot,
C.CLEAUD

&ANALYZE-SUSPEND _VERSION-NUMBER AB_v10r12 GUI
&ANALYZE-RESUME
/* Connected Databases 
    mydatabase
*/
&Scoped-define WINDOW-NAME C-Win
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _DEFINITIONS C-Win

**Comment by jcaillon** [comment]
I'm closing this issue, this information is only used by the appbuilder and I don't see the point of this feature since the tables used in the program are already displayed in the code explorer. Sorry!

**Comment by ccleaud** [comment]
Please consider this ticket.
