### ISSUE TITLE
Enahncement: connect 3P to a database otherwise than via a .pf file

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#94]
I have to connect to a database whose connection string is hard-coded in a script file.
I didn't find any way with 3P to connect to database without creating a .pf file and referencing it into 3P settings.
Could you add this feature please?

Best regards.
C.CLEAUD

**Comment by jcaillon** [comment]
See "extra connections" in the Set -> Environnement page interface : 

![image](https://cloud.githubusercontent.com/assets/11553075/21500081/9cd41ade-cc3b-11e6-959f-c9f593fb3592.png)
