### ISSUE TITLE
Child Progress sessions display icon in task bar

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#97]
All in the title.

This happens when checking version and also when compiling. But I was unable to capture screen when compiling so I only give you a screenshot when checking version.

Reproduced on a virtualized Windows XP.
Maybe that's why I had time to capture the screen.

![5](https://cloud.githubusercontent.com/assets/7109720/19417010/53aae270-93a1-11e6-8340-f08a79b65b4d.PNG)

Using version 3P 1.7.0.

**Comment by jcaillon** [comment]
See this option : 

![image](https://cloud.githubusercontent.com/assets/11553075/21507026/47bf0bf0-cc75-11e6-8a99-1e84dd745d95.png)
