### ISSUE TITLE
Error notification popups don't auto-hide

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#99]
This is annoying, especially when working with a laptop in the case where an external screen was plugged and Notepad++ run on it then external screen unplugged.

In such case, those unclosed notifications are partially outside the laptop screen and the close button is NOT reachable and the notification don't auto close and the notification is a top-most window.

Thanks for fixing.
Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
Notifications can now be closed with the ESCAPE key while focusing them (as of 1.7.1).
I will also probably add a context menu with the option to close/close visible/close all
